### ISSUE TITLE
Payroll AU issues

### ISSUE THREAD

**Issue by pauliak1** [XeroAPI/xero-php-oauth2#100]
I get the following error:

Fatal error: Uncaught Error: Call to undefined method XeroAPI\XeroPHP\Configuration::getHostPayrollAu() 

looks like the host for PayrollAu is missing from Configuration file

**Comment by SidneyAllen** [comment]
@pauliak1 - thanks for catching this.  I've added the missing method in Configuration and tested. Fixed in version 1.5.2
