### ISSUE TITLE
PayrollAU getPayItems Issue

### ISSUE THREAD

**Issue by pauliak1** [XeroAPI/xero-php-oauth2#101]
I get the following error when running getPayItems:

Fatal error: Uncaught InvalidArgumentException: Invalid value for enum '\XeroAPI\XeroPHP\Models\PayrollAu\EarningsType', must be one of: 'FIXED', 'ORDINARYTIMEEARNINGS', 'OVERTIMEEARNINGS', 'ALLOWANCE', 'LUMPSUMD', 'EMPLOYMENTTERMINATIONPAYMENT' in /var/www/vendor/xeroapi/xero-php-oauth2/lib/PayrollAuObjectSerializer.php:336

looks like at least 'LUMPSUMA' and 'LUMPSUMB' (might be others) are missing from EarningsType.php

**Comment by SidneyAllen** [comment]
@pauliak1 I'll be updating our OpenAPI specs and adding these.  Keep the feedback coming.

We will update the SDK when we release v 2.0.9 of our OpenAPI spec tomorrow.

**Comment by SidneyAllen** [comment]
@pauliak1 resolved in version 1.5.3 - thanks

https://github.com/XeroAPI/xero-php-oauth2/releases/tag/1.5.3
