### ISSUE TITLE
Cannot connect with Access token

### ISSUE THREAD

**Issue by maheshemvigo** [XeroAPI/xero-php-oauth2#104]
After create access token get data using with that token i got error , iam usnig same code as in example,
$config = XeroAPI\XeroPHP\Configuration::getDefaultConfiguration()->setAccessToken( (string)$accessToken->getToken() );
      $identityApi = new XeroAPI\XeroPHP\Api\IdentityApi(
        new GuzzleHttp\Client(),
        $config
      );
      $result = $identityApi->getConnections();

Please help me

**Comment by MattR-Api** [comment]
Hi @maheshemvigo 

As this isn't an issue directly related to the PHP SDK, just the access token being used, I'll close the issue off. However, if you could please get in touch with us at api@xero.com,with the following information, we'll be happy to help.

- The Name of the App
- The Apps Client ID (OAuth 2.0)
- ​​​​​​​The Organisation Name you’re attempting to connect to (as it appears in Xero)
- The Authorisation URL you’re generating to access the Organisation Select Screen

Once we have the above, we'll be more than happy to investigate further. 

Cheers

Matt

**Comment by maheshemvigo** [comment]
Hi,
Now i am testing with demo app. if it will success then only we will use
the original one.
My demo information s below,
'clientId' => '5F88D508A90944529376D0D09777EE7C',
'clientSecret'=> '10P46ECLZFgTDL3lSVGmIfFk3asP0Az6dxmsrOeNUoAm8Mxo',
'redirectUri' => 'http://localhost:8000/testApi'

Please give me the sdk formate for accessing data with access key.Is it
possible to access data with demo app using access key.
If you need the original xero id what we going use i will give.
Thank you
