### ISSUE TITLE
Update date format from MicrosoftDateFormat to ISO 8601

### ISSUE THREAD

**Issue by pauliak1** [XeroAPI/xero-php-oauth2#107]
The MicrosoftDateFormat (e.g. /Date(1198908717056+0000)/ ) used throughout the API is extremely old and is now deprecated. Would be great to update to ISO 8601 format "2020-04-15T02:37:09+00:00"

**Comment by SidneyAllen** [comment]
@pauliak1 - thanks for the feedback, this isn't a change that is related to this SDK and is probably best voiced at https://xero.uservoice.com/forums/5528-xero-accounting-api/suggestions/34192549-supply-non-net-date-format-via-api

For now, I'll be looking for ways to provide native date support in our SDKs by converting Microsoft DateFormat.
