### ISSUE TITLE
SDK not able to handle Xero organisations with Domestic Reverse tax rates

### ISSUE THREAD

**Issue by fooman** [XeroAPI/xero-php-oauth2#109]
**SDK you're using (please complete the following information):**
 - most recent

**Describe the bug**
Retrieving tax rates from UK organisation fails with `Invalid value for 'report_tax_type', must be one of`

**To Reproduce**
1. Connect SDK to Xero UK organisation (my test UK organisation does not exhibit this so I am not sure what else is needed to create this)
2. Retrieve Tax Rates

**Expected behavior**
The SDK can communicate with all Xero account types.

**Additional context**
The following types (at least) seem to be missing     
```
const REPORT_TAX_TYPE_DRCHARGESUPPLY = 'DRCHARGESUPPLY';
const REPORT_TAX_TYPE_DRCHARGE = 'DRCHARGE';
```
Please note these are also undocumented on https://developer.xero.com/documentation/api/types

**Comment by fooman** [comment]
It's these ones:
![image](https://user-images.githubusercontent.com/455508/80559819-fb757c00-8a32-11ea-8845-c292a1353373.png)

**Comment by wobinb** [comment]
Hi Fooman

Thank you for spotting and documenting this. This SDK (and the others) are auto generated from our OpenAPI spec. As such we need to update that with the new tax rates, which will then filter down into the SDKs the next time we generate it.

I've made the update here: https://github.com/XeroAPI/Xero-OpenAPI/pull/197 so it should just be a case of waiting until it filters down. 

In the meantime you could make a manual update to https://github.com/XeroAPI/xero-php-oauth2/blob/master/lib/Models/Accounting/TaxType.php to add the following tax types:
DRCHARGESUPPLY20
DRCHARGE20
DRCHARGESUPPLY5
DRCHARGE5

**Comment by wobinb** [comment]
The lasted changes from the OpenAPI spec have been incorporated into the latest update (https://github.com/XeroAPI/xero-php-oauth2/pull/110), so this should now be fixed.
