### ISSUE TITLE
401 error when I try to use createInvoice exactly as done in the docs

### ISSUE THREAD

**Issue by cmklyon** [XeroAPI/xero-php-oauth2#11]
Hi there, I am able to authenticate correctly however when i try to create an invoice or do anything shown on the docs I get multiple errors, mainly 401 errors... example shown below

Exception when calling AccountingApi->createAccount: [401] Client error: `PUT https://api.xero.com/api.xro/2.0/Accounts` resulted in a `401 Unauthorized` response: {"title":"Unauthorized","status":401,"detail":"AuthenticationUnsuccessful","instance":"af9f637f-606d-4778-b7b2-7e6c7b533 (truncated...)

link to used docs;
https://github.com/XeroAPI/xero-php-oauth2/blob/master/docs/Api/AccountingApi.md#createInvoice

Am I missing something significant?
Thank you

**Comment by wobinb** [comment]
The first thing I would check is that you've correctly specified the xero_tenant_id. Are you able to retrieve the list of organisations you are connected to?

**Comment by cmklyon** [comment]
It seems that the get.php doesn't return a list of organisations, I am unsure how to obtain a correct xero_tenant_id, I've seen that I need to retrieve it from the "https://api.xero.com/connections" page, but its not entirely clear how to do so.

**Comment by cmklyon** [comment]
I've managed to get the correct xero_tenant_id, but the line;

	$result = $apiInstance->createInvoice($xero_tenant_id, $invoices);

in my file (similar to https://github.com/XeroAPI/xero-php-oauth2/blob/master/docs/Api/AccountingApi.md#createInvoice )throws the exception;

XeroAPI\XeroPHP\ApiException: [401] Client error: `PUT https://api.xero.com/Invoices` resulted in a `401 Unauthorized` response: {"title":"Unauthorized","status":401,"detail":"AuthenticationUnsuccessful","instance":"a9583570-8349-40f8-9705-dcc72cbca (truncated...) in /home/mike/code/mike/xerotest/xero-php-oauth2-app-master/xero-php-oauth2-app-master/vendor/xeroapi/xero-php-oauth2/lib/Api/AccountingApi.php:9041 Stack trace: #0 /home/mike/code/mike/xerotest/xero-php-oauth2-app-master/xero-php-oauth2-app-master/vendor/xeroapi/xero-php-oauth2/lib/Api/AccountingApi.php(9016): XeroAPI\XeroPHP\Api\AccountingApi->createInvoiceWithHttpInfo('24b0c6cc-a192-4...', Array) #1 /home/mike/code/mike/xerotest/xero-php-oauth2-app-master/xero-php-oauth2-app-master/myXeroFile.php(33): XeroAPI\XeroPHP\Api\AccountingApi->createInvoice('24b0c6cc-a192-4...', Array) #2 {main}

Lastly in the docs it says that the array for the line item should come from;
         \XeroAPI\XeroPHP\Models\Accounting\Invoices 
but this path doesn't exist

Thanks for all the help

**Comment by SidneyAllen** [comment]
Hi @cmklyon 

In the code below, we call "getConnections" to get an ARRAY of orgs you've authorized.  The sample code just grabs the first org in that array to get a valid XeroTenantId and saves it along with your accessToken information.   

This is example code, you'll need to make sure you're using the correct tenant id if you authorize a user who has access to more than one org
$result[0]->getTenantId() vs. $result[1]->getTenantId() 

$config = XeroAPI\XeroPHP\Configuration::getDefaultConfiguration()->setAccessToken( (string)$accessToken->getToken() );
          
      $config->setHost("https://api.xero.com"); 
      $identityInstance = new XeroAPI\XeroPHP\Api\IdentityApi(
        new GuzzleHttp\Client(),
        $config
      );
       
      $result = $identityInstance->getConnections();

      // Save my token, expiration and tenant_id
      $storage->setToken(
          $accessToken->getToken(),
          $accessToken->getExpires(),
          $result[0]->getTenantId(),  
          $accessToken->getRefreshToken()
      );

Not sure why you are getting a 401, if you are using a valid access token and xeroTenantId.

Once you get past that, I recommend checking out our kitchen sync app for example of how to interact with different endpoints - https://github.com/XeroAPI/xero-php-oauth2-app

Creating an invoice will look something like this ... 

$lineitem = new XeroAPI\XeroPHP\Models\Accounting\LineItem;
$lineitem->setDescription('Sample Item')
	->setQuantity(1)
	->setUnitAmount(20)
	->setAccountCode("400");

$getContact = $this->getContact($xeroTenantId,$apiInstance,true);
$contactId = $getContact->getContacts()[0]->getContactId();
$contact = new XeroAPI\XeroPHP\Models\Accounting\Contact;
$contact->setContactId($contactId);

$invoice = new XeroAPI\XeroPHP\Models\Accounting\Invoice;
$invoice->setReference('Ref-001')
	->setDueDate(new DateTime('2018-01-02'))
	->setContact($contact)
	->setLineItems($lineitems)
	->setStatus(XeroAPI\XeroPHP\Models\Accounting\Invoice::STATUS_DRAFT)
	->setType(XeroAPI\XeroPHP\Models\Accounting\Invoice::TYPE_ACCPAY)
	->setLineAmountTypes(\XeroAPI\XeroPHP\Models\Accounting\LineAmountTypes::EXCLUSIVE);
$result = $apiInstance->createInvoice($xeroTenantId,$invoice); 

$result->getInvoices()[0]->getTotal()
