### ISSUE TITLE
Every Accounting model's getIterator() is incorrect

### ISSUE THREAD

**Issue by filliph** [XeroAPI/xero-php-oauth2#114]
**SDK you're using (please complete the following information):**
 - 1.6.2

**Describe the bug**
If you open up any accounting model that has a `getIterator()` function in an IDE, you'll receive an error message due to namespaces on the `ArrayIterator` object being returned.

**To Reproduce**
1. Update to 1.6.2
2. Open up any of the Accounting models with a `getIterator()` function
3. See error

**Expected behavior**
The code should read `return new \ArrayIterator` not `return new ArrayIterator(`

**Comment by SidneyAllen** [comment]
@filliph - thanks for catching that.  Check out version 1.6.3
https://github.com/XeroAPI/xero-php-oauth2/releases/tag/1.6.3
