### ISSUE TITLE
Call to undefined function random_bytes()

### ISSUE THREAD

**Issue by Sandeep-MWP** [XeroAPI/xero-php-oauth2#116]
**SDK you're using (please complete the following information):**
 - Using  xeroapi/xero-php-oauth2 sdk version 1.6 and
- Using Php version 5.6 Php 

**Is your feature request related to a problem? Please describe.**
- thank you for updating and giving support for xero-php-oauth2 sdk version 1.6 with php 5.6. But it seems there is still some function used within the sdk that donot support php 5.6. 
- We are getting error
-"Call to undefined function random_bytes()" 
- random_bytes() seems to be php 7's function.
- We get error, when we try to get authorizationURL i.e. getAuthorizationUrl() > getAuthorizationParameters() > getRandomState() > return bin2hex(random_bytes($length / 2));
  - $authorizationUrl = $provider->getAuthorizationUrl($options);

**Describe the solution you'd like**
- Could you please update the random_bytes() to some function that support Php 5.6.

`/**
     * Returns a new random string to use as the state parameter in an
     * authorization flow.
     *
     * @param  int $length Length of the random string to be generated.
     * @return string
     */
    protected function getRandomState($length = 32)
    {
        // Converting bytes to hex will always double length. Hence, we can reduce
        // the amount of bytes by half to produce the correct length.
        return bin2hex(random_bytes($length / 2));
    }`

**Comment by SidneyAllen** [comment]
Hi @Sandeep-MWP 

The error you are seeing is related to the league/oauth2-client dependency.

I've confirmed the SDK works with PHP 5.6.32
you can watch this video to see how I install dependencies https://www.youtube.com/watch?v=S137G35eFRI

**Comment by Sandeep-MWP** [comment]
Thank you @SidneyAllen,

After installing paragonie/random_compat:\<9.99 solves the problem.

Much appreciated.
