### ISSUE TITLE
createInvoice() causes server to freeze with error " A session had already been started - ignoring session_start()"

### ISSUE THREAD

**Issue by cmklyon** [XeroAPI/xero-php-oauth2#12]
I am able to succesfully get a JSON of the correct invoices when I use lines like;
`$apiResponseInvoices = $apiInstance->getInvoices($xeroTenantId); `

However, when I try to create an invoice, using;
`try {`
    `$result = $apiInstance->createInvoice($xeroTenantId, $invoice);`
   ` print_r($result);`
`} catch (Exception $e) {`
    `//echo 'Exception when calling AccountingApi->createInvoice: ', $e->getMessage(), PHP_EOL;`
   ` echo $e;`
`}`

with my JSON as the `  $inovice ` variable, the server freezes I get the following error;

`[27-Nov-2019 15:07:50 UTC] PHP Notice:  A session had already been started - ignoring session_start() in *myPath*/xero-php-oauth2-app-master/xero-php-oauth2-app-master/authorization.php on line 9`

`[27-Nov-2019 15:07:50 UTC] PHP Stack trace:`

`[27-Nov-2019 15:07:50 UTC] PHP   1. {main}() *myPath*/xero-php-oauth2-app-master/xero-php-oauth2-app-master/authorization.php:0`

`[27-Nov-2019 15:07:50 UTC] PHP   2. session_start() *myPath*/xero-php-oauth2-app-master/xero-php-oauth2-app-master/authorization.php:9`

If I enter my JSON/XML as a string it gives the error;

`PUT https://api.xero.com/api.xro/2.0/Invoices resulted in a 400 Bad Request response: { "ErrorNumber": 17, "Type": "NoDataProcessedException"`

How am I supposed to correctly create an invoice?
Thanks in advance

**Comment by SidneyAllen** [comment]
@cmklyon - Thanks fro the feedback.

The $invoice variable should not be raw JSON, but should be an instance of the invoice model.  I'll keep this issue open so we can add some more robust examples of API calls.

A bit confused about the error.
PHP Notice: A session had already been started - ignoring session_start() in *myPath*/xero-php-oauth2-app-master/xero-php-oauth2-app-master/authorization.php on line 9

Not sure if this is related - but in the README the code used to make API calls after you obtain an access token are on authorizedResource.php.

So I would expect you'd be making API calls from a PHP page other than authorization.php

**Comment by PHPwiz-web** [comment]
Hi,

I am having the same issue while creating an invoice.

Error says Client error: `PUT https://api.xero.com/api.xro/2.0/Invoices` resulted in a `400 Bad Request` response: { "ErrorNumber": 17, "Type": "NoDataProcessedException", "Message": "No data has been processed for this endpoi (truncated...) 

Could you provide an example of the raw JSON that needs to be passed to the method?

Thanks,

**Comment by SidneyAllen** [comment]
Hi @PHPwiz-web 

Here is an example of how to create ONE Invoice using method "createInvoice"


$where = 'ContactStatus=="ACTIVE"';
$getContact = $apiInstance->getContacts($xeroTenantId, null, $where); 
$contactId = $getContact->getContacts()[0]->getContactId();

$contact = new XeroAPI\XeroPHP\Models\Accounting\Contact;
$contact->setContactId($contactId);

$lineitem = new XeroAPI\XeroPHP\Models\Accounting\LineItem;
$lineitem->setDescription('Sample Item')
    ->setQuantity(1)
    ->setUnitAmount(20)
    ->setAccountCode("400");
$lineitems = [];    
array_push($lineitems, $lineitem);

$invoice = new XeroAPI\XeroPHP\Models\Accounting\Invoice;
$invoice->setReference('Ref-num')
  ->setDueDate(new DateTime('2017-01-02'))
  ->setContact($contact)
  ->setLineItems($lineitems)
  ->setStatus(XeroAPI\XeroPHP\Models\Accounting\Invoice::STATUS_AUTHORISED)
  ->setType(XeroAPI\XeroPHP\Models\Accounting\Invoice::TYPE_ACCPAY)
  ->setLineAmountTypes(\XeroAPI\XeroPHP\Models\Accounting\LineAmountTypes::EXCLUSIVE);

try {
    $result = $apiInstance->createInvoice($xero_tenant_id, $invoice);
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling AccountingApi->createInvoice: ', $e->getMessage(), PHP_EOL;
}

and here is an example creating MULTIPLE invoices (I add the same invoice data to the array of Invoices) using method "createInvoices"

$where = 'ContactStatus=="ACTIVE"';
$getContact = $apiInstance->getContacts($xero_tenant_id, null, $where); 
$contactId = $getContact->getContacts()[0]->getContactId();

$contact = new XeroAPI\XeroPHP\Models\Accounting\Contact;
$contact->setContactId($contactId);

$lineitem = new XeroAPI\XeroPHP\Models\Accounting\LineItem;
$lineitem->setDescription('Sample Item')
    ->setQuantity(1)
    ->setUnitAmount(20)
    ->setAccountCode("400");
$lineitems = [];    
array_push($lineitems, $lineitem);

$invoice = new XeroAPI\XeroPHP\Models\Accounting\Invoice;
$invoice->setReference('Ref-num')
  ->setDueDate(new DateTime('2017-01-02'))
  ->setContact($contact)
  ->setLineItems($lineitems)
  ->setStatus(XeroAPI\XeroPHP\Models\Accounting\Invoice::STATUS_AUTHORISED)
  ->setType(XeroAPI\XeroPHP\Models\Accounting\Invoice::TYPE_ACCPAY)
  ->setLineAmountTypes(\XeroAPI\XeroPHP\Models\Accounting\LineAmountTypes::EXCLUSIVE);

$arr_invoices = [];   
array_push($arr_invoices, $invoice);
array_push($arr_invoices, $invoice);
$invoices = new XeroAPI\XeroPHP\Models\Accounting\Invoices;
$invoices->setInvoices($arr_invoices);

try {
    $result = $apiInstance->createInvoices($xero_tenant_id, $invoices, true);
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling AccountingApi->createInvoices: ', $e->getMessage(), PHP_EOL;
}

**Comment by sdeering** [comment]
In-case someone else encounters this error this is how you can debug it.

debug here: vendor/xeroapi/xero-php-oauth2/lib/Api/AccountingApi.php:7477

add

`dd($e->getResponse()->getBody()->getContents());`

in my case i could see the validation error due date must be set... nothing in the API about this being a required field...
