### ISSUE TITLE
Api/PayrollAuApi.php needs to be renamed for composer2 compatibility

### ISSUE THREAD

**Issue by hailwood** [XeroAPI/xero-php-oauth2#124]
**SDK you're using (please complete the following information):**
 - Version 1.6.5

**Describe the bug**
Composer 2 only autoloads via PSR-4. However the file Api/PayrollAuApi.php will not autoload as while the filename is PayrollA**u**Api the class name is PayrollA**U**Api.

The file needs to be renamed so it's casing matches the class.

![image](https://user-images.githubusercontent.com/709773/82775794-e4dd0c00-9e9c-11ea-83e2-9c6cadf29e22.png)

**Comment by SidneyAllen** [comment]
@hailwood - addressed in version 2.0.0
https://github.com/XeroAPI/xero-php-oauth2/releases/tag/2.0.0
