### ISSUE TITLE
connecting to XERO OAuth2 API without UI

### ISSUE THREAD

**Issue by Sandeep-MWP** [XeroAPI/xero-php-oauth2#125]
Hi,

Do you have any immediate future plans for silently (without UI) connecting/authorization in the OAuth2 API.

Thanks

**Comment by wobinb** [comment]
Hi Sandeep

Once your app has completed the authorisation process it can maintain a near-permanent connection by refreshing the tokens. So long as this is done at least once every 60 days, you shouldn't have any issues. The following links contain further detail:
https://developer.xero.com/documentation/api-guides/machine-2-machine
https://developer.xero.com/documentation/oauth2/auth-flow

In the meantime I'll close this issue as it isn't specific to the PHP SDK.
