### ISSUE TITLE
Create Leave Application - Payroll AU - Error 500 / Bad Request 400

### ISSUE THREAD

**Issue by usmanmunirr** [XeroAPI/xero-php-oauth2#126]
**SDK you're using**
 - Version [e.g. 1.6.5]

**Describe the bug**
I am not able to create leave application for employee via createLeaveApplication() - the error i get is 500 server error or bad request 400

**To Reproduce**
1. Go to createleaveApplication() / Pass the tenant id and leave application details at function params
2. Click on createleaveApplication()
3. Submit request using the $apiInstance->createleaveApplication() method.

**Expected behavior**
I would expect for the leave to be created via createLeaveApplication() function

      $leave_application = [ `{ 
        "EmployeeID": "a416a8fe-0876-462e-bef8-690beacbfc4f", 
        "LeaveTypeID": "771c622a-c596-4816-b061-9445d969908f", 
        "Title": "Hello World", 
        "StartDate": "2020-05-20", 
        "EndDate": "2020-05-22" 
      }`
    ]; 
      try {
        $result = $apiInstance->createLeaveApplication($xero_tenant_id, $leave_application);
        var_dump($result);
      } catch (Exception $e) {
        print_r($e);
      }
    

ERROR
**Screenshots**
![image](https://user-images.githubusercontent.com/54349061/83383141-ddcb7600-a427-11ea-9e6a-4e5022e58ee0.png)

**Additional context**

**Comment by SidneyAllen** [comment]
@usmanmunirr - below is an example how to structure your call to createLeaveApplication.

use XeroAPI\XeroPHP\PayrollAuObjectSerializer;

$leaveapplication = new XeroAPI\XeroPHP\Models\PayrollAu\LeaveApplication;
$leaveapplication->setDescription("Fred");
$leaveapplication->setEmployeeID($employeeId);  // you'll need to GET this value
$leaveapplication->setLeaveTypeID($leaveTypeId);   // you'll need to GET this value
$leaveapplication->setStartDateAsDate(new DateTime('2020-05-02'));
$leaveapplication->setEndDateAsDate(new DateTime('2020-05-12'));

$arr_leaveapplications = [];		
array_push($arr_leaveapplications, $leaveapplication);

try {
	$result = $payrollAuApi->createLeaveApplication($xeroTenantId, $arr_leaveapplications);
} catch (\XeroAPI\XeroPHP\ApiException $e) {
	$error = PayrollAuObjectSerializer::deserialize($e->getResponseBody(), '\XeroAPI\XeroPHP\Models\PayrollAu\APIException',[]);
	var_dump($error->getMessage() );
}
