### ISSUE TITLE
Manual Journal

### ISSUE THREAD

**Issue by ponel-reston** [XeroAPI/xero-php-oauth2#129]
**SDK you're using (please complete the following information):**
 - Version ^1.0

**Describe the bug**
Manual journal works for 2 months more, but suddenly not working anymore

**Expected behavior**
Manual journal should be drafted 

**Additional context**
No error, the app is connected.
I tested it on demo account, it works.
Any idea?

**Comment by wobinb** [comment]
Can you get in touch with our support team using api@xero.com. Please quote the client id for your app, the organisation it is connected to and the timestamp of the API call.

This should allow us to check our logs and identify why the call isn't working.
