### ISSUE TITLE
Problem Getting Errors for ValidationException

### ISSUE THREAD

**Issue by mmoradeveloper** [XeroAPI/xero-php-oauth2#13]
I am doing an integration and I need to Sync Contacts.
To avoid the 429 Error in that process I am trying to POST the contacts in bulk .
The main problems is that when I receive a 400 Validation Error I can not get all the call informaton.
The only thing I get is  an Exception triggered with the following Message::

string(251) "[400] Client error: `PUT https://api.xero.com/api.xro/2.0/Contacts#bulk` resulted in a `400 Bad Request` response:
{
  "ErrorNumber": 10,
  "Type": "ValidationException",
  "Message": "A validation exception occurred",
  "Elements" (truncated...)
"  

when that happens some of the POST contacts are already created and I need the contact_id (xero unique identifier ) .

So the question is how I can get the full message so I can see which customer is created and which are not.

Thank you

**Comment by mmoradeveloper** [comment]
I realize that there is an ApiException to catch the full error
use XeroAPI\XeroPHP\ApiException;
using the function getResponseBody()

Thanks

**Comment by toby2g** [comment]
@mmoradeveloper Having a similar issue. When you used the getResponseBody function, were those Contacts that saved returned in the response along with the ones that triggered the validation?

I'm only having those that triggered validation returned.

**Comment by mmoradeveloper** [comment]
Hi @toby2g,
As I generate  the new Contact adding a ContactNumber (unique identifier on my DB)
 when an error is triggered on createContacts I manage those Failed Elements returned 
and then by exclusion I get the rest of the Contacts created using the getContact  call calling the  ContactNumber instead of ContactId.

hope that helps .
It was my way around to get back the non failing ContactId's when and erro was triggered.
