### ISSUE TITLE
Schedule Model missing invoice due date types

### ISSUE THREAD

**Issue by andrewerkins** [XeroAPI/xero-php-oauth2#132]
The **Schedule model** currently defines the following due date types for bills -  **DAYSAFTERBILLDATE**, **DAYSAFTERBILLMONTH** but not the corresponding invoice types. 

When fetching repeating invoices, this causes an exception to be thrown by the setter if Xero contains repeating invoices using DAYSAFTERINVOICEDATE or DAYSAFTERINVOICEMONTH

**Comment by SidneyAllen** [comment]
@andrewerkins - added in release 2.0.1
https://github.com/XeroAPI/xero-php-oauth2/releases/tag/2.0.1
