### ISSUE TITLE
unAuthorized request Error

### ISSUE THREAD

**Issue by bilalswiftsolutions** [XeroAPI/xero-php-oauth2#138]
All the credentials are correct still getting this error not sure why it is happening despite of all right credentials

XeroAPI \ XeroPHP \ ApiException (401)
[401] Client error: `PUT https://api.xero.com/api.xro/2.0/Contacts?summarizeErrors=true` resulted in a `401 Unauthorized` response: {"Type":null,"Title":"Unauthorized","Status":401,"Detail":"AuthenticationUnsuccessful","Instance":"1ddb01fb-fff4-4a19-b6 (truncated...)

**Comment by SidneyAllen** [comment]
@bilalswiftsolutions - it sounds like a problem with the scopes when you obtained your access token.

I recommend logging into Xero and navigating to Settings > Connected App and disconnecting your app.

In your code confirm you have the "accounting.contacts" scope is set when you re-authorize your Xero org connection.

**Comment by bilalswiftsolutions** [comment]
I am using wrapper library recommended by this sdk for larvel here is the code

```
  $apiInstance  = resolve(\XeroAPI\XeroPHP\Api\AccountingApi::class);
    
        $contact = resolve( \XeroAPI\XeroPHP\Models\Accounting\Contact::class);
        $contact->setName('asdrtfgbhunjmkl,kmjhnbgbbnbjbbj');
        $contact->setContactId('6d42f03b-181f-43e3-93fb-2025c0hjhe92');
        $apiResponse = $apiInstance->createContacts($xeroCredentials->getTenantId() ,$contact,true);
        $message = 'New Contact Name: ' . $apiResponse->getContacts()[0]->getName();
```

**Comment by bilalswiftsolutions** [comment]
Issue is resolved now i was using wrapper library for laravel in config file xero.php i was needed define scope for contacts ```accounting.contacts```

 ```
 'scopes'                     => [
            'openid',
            'email',
            'profile',
            'offline_access',
            'accounting.settings',
            'accounting.contacts',
        ],
```
