### ISSUE TITLE
League\OAuth2\Client\Provider\Exception\IdentityProviderException: invalid_client

### ISSUE THREAD

**Issue by manojn-arkenea** [XeroAPI/xero-php-oauth2#139]
Hi,

I am getting below error,

ERROR: League\OAuth2\Client\Provider\Exception\IdentityProviderException: invalid_client in /vendor/league/oauth2-client/src/Provider/GenericProvider.php:222

Can anyone idea about this? 

We have 2 servers and this issue is only getting on production server not the development server. 

Thanks in advance

**Comment by SidneyAllen** [comment]
@manojn-arkenea 

Since this works on one server and not the other, this does not sound like an SDK issue, but a server environment issue.

I'm sorry but have not seen this error before.  I'll be closing this as it's not SDK related.
