### ISSUE TITLE
Wrong refund cash currency rate 

### ISSUE THREAD

**Issue by btudor113** [XeroAPI/xero-php-oauth2#143]
When I m exporting credit memos from Magento 2.3.3 into Xero and I m going to credit memo cash refund the currency rate shows 1 euro = 1 dkk. Where I can find where exactly set that currency rate?
![screenshot-go xero com-2020 07 06-09_49_07](https://user-images.githubusercontent.com/66674014/87412586-e2ac4980-c5d1-11ea-8e3f-30179d595e40.png)

**Comment by SidneyAllen** [comment]
@btudor113 - if you are referring to Credit Notes, have a look at the API documentation
https://developer.xero.com/documentation/api/credit-notes#POST

You can set the property ....
CurrencyRate | The currency rate for a multicurrency invoice. If no rate is specified, the XE.com day rate is used

Perhaps your integration is setting the CurrencyRate to 1.0000

If you omit the CurrencyRate property Xero will use XE.com
https://central.xero.com/s/article/About-multicurrency
