### ISSUE TITLE
createContacts doesn't allow for summarizedErrors

### ISSUE THREAD

**Issue by toby2g** [XeroAPI/xero-php-oauth2#15]
I'm trying to use the createContacts function to perform a bulk creation of Contacts.

`$response = $this->xeroApi->createContacts($this->xeroTenantId, $contacts);`

Currently if there are any errors from this request, a 400 response will be return with all the ValidationExceptions listed. Any contacts that were included that did not trigger this validation are created, but no corresponding details are returned.

Would the ability to pass through the 'summarize_errors' parameter, similar to the createInvoices() function be possible? Allowing a 200 response to be returned as well as the corresponding contacts (errors attached to the corresponding contact).

According to the Xero API documentation, https://developer.xero.com/documentation/api/requests-and-responses, this functionality should exist for contacts.

I've personally gone through and added the following to the createContactsRequest function:
`$queryParams['summarizeErrors'] = AccountingObjectSerializer::toQueryValue('false');`

I also had to move the #bulk from the resourcePath
`$resourcePath = '/Contacts';`

Doing this I was able to get the desired result.

**Comment by SidneyAllen** [comment]
Thanks @toby2g 

We've updated our OpenAPI spec we use to generate our SDKs and released 1.0.5 to address this issue.
