### ISSUE TITLE
getLineItems()[item]->getDiscountAmount() is returning empty

### ISSUE THREAD

**Issue by timwiel** [XeroAPI/xero-php-oauth2#152]
**SDK you're using (please complete the following information):**
 - Version 2.1.0

**Describe the bug**
When performing a retrieval of an ACCREC invoice with that has discounted line items only the getDiscountRate is returned and getDiscountAmount is empty.

```PHP
$result = $apiInstance->getInvoices($xeroTenantId,null,null,null,null,'INV-6900');
echo '<pre>';
print_r($result->getInvoices()[0]->getLineItems());
```
However when using the Previewer the XML returns a discountAmount AND discountRate

**Expected behavior**
I would expect that both discountAmount AND discountRate should be returned

**Screenshots**
Xero Invoice Line Items:
![image](https://user-images.githubusercontent.com/21289335/90467525-81dfd600-e168-11ea-8b6d-365aeba84c4b.png)

print_r result from code above:
![image](https://user-images.githubusercontent.com/21289335/90467386-36c5c300-e168-11ea-8d3b-dec62c7e07d7.png)

API previewer on developer.xero.com:
![image](https://user-images.githubusercontent.com/21289335/90467595-acca2a00-e168-11ea-8668-863cb8880402.png)

**Comment by timwiel** [comment]
Note I've tried this in both the example app (where the modified code above lives) and a more developed app - both fail to return the required discountAmount

**Comment by wobinb** [comment]
@timwiel The API server response on the Invoices endpoint will vary depending on the call being made.

When retrieving a single invoice eg. api.xro/2.0/Invoices/c7e6d6b6-f32f-46a5-9e3b-31088fd9193d full detail will be returned. 

If multiple invoices could be returned eg. api.xro/2.0/Invoices?where=InvoiceNumber=='ORC1041' only a summary is returned.

If the page argument is included eg. api.xro/2.0/Invoices?page=1 the response includes more - but not all the detail.

The call you are making uses the InvoiceNumbers argument eg. api.xro/2.0/Invoices?InvoiceNumbers=ORC1041 this gives the same response as the page argument, and crucially doesn't include the DiscountAmount field.

To retrieve the DiscountAmount field try making the call like this:
`$apiResponse = $accountingApi->getInvoice($xeroTenantId,$invoiceId);`

**Comment by timwiel** [comment]
I believe there is still a bug with this issue (not in the SDK but in the API) ... I've posted the a bug report on the API issues list (https://github.com/XeroAPI/Xero-OpenAPI/issues/592#issue-2334350824)
