### ISSUE TITLE
Update league/oauth2-client dependency to 2.5.0 for guzzle7 support

### ISSUE THREAD

**Issue by bumperbox** [XeroAPI/xero-php-oauth2#157]
**Is your feature request related to a problem? Please describe.**
I am having conflicts in composer between packages requiring guzzle6 vs guzzle7 as a requirement

**Describe the solution you'd like**
update dependency on league/oauth2-client to version 2.5.0 which supports guzzle7

**Describe alternatives you've considered**
I have currently forked this project and other related projects and overridden the composer files so i can use guzzle7

**Comment by SidneyAllen** [comment]
@bumperbox - updated in version 2.1.2
