### ISSUE TITLE
IDE can't resolve class: Undefined class 'AccountingApi'

### ISSUE THREAD

**Issue by bluec** [XeroAPI/xero-php-oauth2#158]
**SDK you're using (please complete the following information):**
 - Version 2.1.1

**Describe the bug**

PHPStorm seems unable to resolve the `XeroAPI\XeroPHP\Api\AccountingApi` class. It just shows _Undefined class 'AccountingApi'_ and therefore can't autocomplete any of the methods etc. Have invalidated the caches in PHPStorm but this does not fix it. Have also forced `composer dump-autoload` but that hasn't fixed it either. 

The namespace and class name look correct to me, and the autoload in `composer.json` looks ok so I am really baffled about what is causing this error. I don't know whether there is something wrong with this library or whether this is a PHPStorm bug.

**To Reproduce**

1. Create new project in PHPStorm
2. Install version 2.1.1 of this library using composer
3. Create a new class and try to reference `XeroAPI\XeroPHP\Api\AccountingApi` e.g. in a `use` statement
4. See "Undefined class" error, no autocompletion or type hinting or any IDE goodness for methods in that class

**Expected behavior**

Expect the class to be resolved properly

**Additional context**

I am not the only person with this issue as can be seen here https://community.xero.com/developer/discussion/118717518

**Comment by bluec** [comment]
Been looking at this and I had a hunch that the enormous size of `XeroAPI\XeroPHP\Api\AccountingApi` (58,000 lines and 2.7MB) might be a factor. I reduced the file to roughly half the size (26,000 lines) and after doing so PHPStorm can instantly resolve the class properly.

So, I guess the file is hitting some sort of limit in Jetbrains/PHPStorm. I will investigate further.

**Comment by bluec** [comment]
This is actually a PHPStorm configuration issue and there is no problem with the code. I will leave the fix here for other people.

The `XeroAPI\XeroPHP\Api\AccountingApi` class file exceeds the default 2500 kilobyte maximum size that Intellisense will work with.

To fix this, add the following to the idea.properties file to increase this limit to 5000 kilobytes

```
# Maximum file size (kilobytes) IDE should provide code assistance for.
idea.max.intellisense.filesize=5000
```

Instructions here for configuring platform properties on Mac/Windows/Linux:

https://www.jetbrains.com/help/phpstorm/tuning-the-ide.html#configure-platform-properties

**Comment by SidneyAllen** [comment]
@bluec - this has been reported in another issue.  I have updated the README about PHPStorm and how to update the filesize limit.  Thanks for the link.

**Comment by ryanhungate** [comment]
Thanks - Learn something new every day. It's completely unrelated to this specific class, but related because of the size itself... great stuff. 👍
