### ISSUE TITLE
Error messaging could be improved

### ISSUE THREAD

**Issue by fooman** [XeroAPI/xero-php-oauth2#161]
**SDK you're using (please complete the following information):**
 - Version [e.g. 2.1.x]

**Describe the bug**
While investigating https://github.com/XeroAPI/xero-php-oauth2/issues/159, https://github.com/XeroAPI/xero-php-oauth2/issues/109 and https://github.com/XeroAPI/xero-php-oauth2/issues/32 I had to edit the api client to get to the bottom of the issue. It would be good if for example the error message here 
https://github.com/XeroAPI/xero-php-oauth2/blob/c07ed298d2ec11dae02fd9d5954214b436ded060/lib/Models/Accounting/Account.php#L493 would include the account and the offending code, similar for other validation errors.

**To Reproduce**
1. see linked issues

**Expected behavior**
Display the offending entry (ie which account and what code).

**Comment by SidneyAllen** [comment]
@fooman - I've removed the 10 char max limit from our OpenAPI spec because while that is true going into the API, it's not true when returning data from the API.

Update in 2.1.3
https://github.com/XeroAPI/xero-php-oauth2/releases/tag/2.1.3
