### ISSUE TITLE
Just wondering when using the $where parameter, what is the syntax when finding by more than one field

### ISSUE THREAD

**Issue by Budrose** [XeroAPI/xero-php-oauth2#162]
**SDK you're using (please complete the following information):**
 - Version [e.g. 1.x.x]

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SidneyAllen** [comment]
@Budrose 

If you wanted to use the where clause to GET all ACCOUNTs where the status is active and type is bank you'd use the following .

    $where = 'Status=="' . \XeroAPI\XeroPHP\Models\Accounting\Account::STATUS_ACTIVE .'" AND Type=="' .  \XeroAPI\XeroPHP\Models\Accounting\Account::BANK_ACCOUNT_TYPE_BANK . '"';
    $result = $apiInstance->getAccounts($xeroTenantId, null, $where);
