### ISSUE TITLE
Can you upgrade guzzlehttp/guzzle to 7 version for support Laravel 8 ?

### ISSUE THREAD

**Issue by nesh-ua** [XeroAPI/xero-php-oauth2#163]

**Comment by fooman** [comment]
if this goes ahead please cover both 6 and 7 `"guzzlehttp/guzzle": "^6.2 | ^7.0",`

**Comment by SidneyAllen** [comment]
@nesh-ua and @fooman 

I've followed your recommendation Kristof and update the composer dependency to support both 6.2 and 7.0

in version 2.1.3 of xero-php-oauth2
