### ISSUE TITLE
Are you going to add password / client credentials grant to your OAuth2 server?

### ISSUE THREAD

**Issue by nesh-ua** [XeroAPI/xero-php-oauth2#164]
Now i have some issues with this. I need to get token without browser (auto code grant type). I have console command, which communicate with your API, and i need to get token in console command

**Comment by SidneyAllen** [comment]
@nesh-ua 

Xero's API does not support the client credential grant and you'll need to go through the OAuth 2 flow at least once to obtain an access token and refresh token for use.  You'll also need to save these tokens and be able to refresh and update them when they expire.  

Here are a resources  to help you obtain an access token.
https://developer.xero.com/documentation/api-guides/machine-2-machine

**Comment by nesh-ua** [comment]
@SidneyAllen 
I already implemented logic, which you offered, but my issues is: i don't use token very often. And my token will be expired someday. And i will have to get token again via auth code flow.
