### ISSUE TITLE
Curl Error

### ISSUE THREAD

**Issue by abhinavrazz7272** [XeroAPI/xero-php-oauth2#166]
- Version 1.1.2

XERO REFRESH TOKEN EXCEPTION cURL error 6: Could not resolve host: identity.xero.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by SidneyAllen** [comment]
@abhinavrazz7272 - I'm not answer your question, but I would recommend upgrading to the current version of the SDK (2.1.3) and having look at our PHP starter project which includes some sample code for performing a token refresh.

https://github.com/XeroAPI/xero-php-oauth2-starter/blob/26f7a8ed2ebd76e449748359611498692bbd72a1/authorizedResource.php#L13
