### ISSUE TITLE
Incorrect maximum length of batch payment details

### ISSUE THREAD

**Issue by awhitby** [XeroAPI/xero-php-oauth2#173]
**SDK you're using (please complete the following information):**
 - Version 2.1.0

**Describe the bug**
BatchPaymentDetails line 318 has a maximum length of 18 characters for the details, but our customers have payments in Xero with details longer than that already. It causes the library to throw an exception when retrieving an EXISTING invoice from xero

**To Reproduce**
Fetch an invoice from xero that has payment details longer than 18 characters

**Expected behavior**
It shouldn't error, the data already exists in Xero so the validation in the php library should match the validation inside Xero. Or not exist at all, there is no reason to validate data that ALREADY exists within xero.

            throw new \InvalidArgumentException('invalid length for $details when calling BatchPaymentDetails., must be smaller than or equal to 18.');

**Comment by micmek** [comment]
This is very similar to my issue:
https://github.com/XeroAPI/xero-php-oauth2/issues/174

**Comment by SidneyAllen** [comment]
Hi @micmek 

We've addressed this in our OpenAPI spec and should be fixed in our next release of xero-php-oauth2
https://github.com/XeroAPI/Xero-OpenAPI/releases/tag/2.3.5

**Comment by SidneyAllen** [comment]
@awhitby - Thanks for the issue.  We've addressed this in version 2.1.5 of the sdk.

https://github.com/XeroAPI/xero-php-oauth2/releases/tag/2.1.5
