### ISSUE TITLE
Which tenant was just authorised?

### ISSUE THREAD

**Issue by andyunleashed** [XeroAPI/xero-php-oauth2#18]
Following the guide and the `$result = $identityInstance->getConnections();` returns an array of tenant ids the app has access to.

However, what it doesn't tell you is which tenant ID was just authorised by the user. Relying on the order doesn't work either because if you disconnect one and add one back it returns to its original position rather than being last or first in the array.

So in essence the question is when retrieving the list of connections, how can we tell which one was just allowed?

**Comment by MattR-Api** [comment]
Hi @andyunleashed 

Thanks for getting in touch. 

This isn't a PHP specific issue as currently the connections endpoint only displays the Tenant ID, the Connection ID, the first connection date and the updated date. This does make it a bit hard to differentiate between the Connected Organisations, however adding the Organisation Name to the Endpoint is on our current development roadmap.

As a workaround in the meantime, the easiest option to recognise each Organisation you're connected to is to iterate through your Connected Tenant ID's and call each Tenants Organisation Endpoint to find the Organisation Name. You can then store that name against the Tenant ID on your apps side.

If you have any further questions, please feel free to raise a case on central.xero.com. or email us at api@support.xero.com. 

Cheers!

Matt

**Comment by andyunleashed** [comment]
Thanks @MattR-Api - if possible I think it would be best if they can return the tokens or some other identifier that is mappable to the original request rather than the name, as potentially the name could be different right?

**Comment by MattR-Api** [comment]
Hi @andyunleashed 

I'm not sure I understand your question. 

You will receive a unique Connection ID (which may be what you're referencing) and Tenant/Organiation ID when calling the connections Endpoint for each Organisation, I'm not sure what other unique ID you could be referring to or want included? You'll also receive the first connection Date which will also be unique (as you currently can't connect multiple Organisations at once).

The plan isn't to remove these IDs, simply also add the Organisation Name to help your identify which Organisation is which at a glance, without having to cross reference.

Please let me know if that helps. 

Kind Regards

Matt

**Comment by andyunleashed** [comment]
@MattR-Api - maybe I misunderstood your original reply, as you mentioned receiving the organisation name back only. But basically the current issue is that you get back an array of _all_ existing connections rather than just one tenant ID. So you have to loop through existing connections to compare, which isn't possible in a multi-tenant environment.

What needs to come back is basically just the tenant ID that you just connected to, which can then be used for mapping.

What I meant by "the name might be different" - is that in Xero you may have called your company "Awesome Sandwiches Limited" - but in the external system, maybe you did "Awesome Sandwiches Ltd" or something, so the name isn't necessarily useful to help map the tenant IDs.

**Comment by SidneyAllen** [comment]
Hi @andyunleashed 

The connection object has two new attributes 

createdDateUtc
updatedDateUtc

You could use these to retrieve the most recent connection

**Comment by andyunleashed** [comment]
Thanks @SidneyAllen - would the createdDate be the initial connection date (in the event of a re-connection), or would the createdDate always be the current connection? (I also imagine the updatedDate is going to be "now").

**Comment by ssta604** [comment]
Would it be possible to add the TenantId to the auth callback?  This would be safer than relying on the created date.

**Comment by RettBehrens** [comment]
The createdDate is the initial connection. The most recent updatedDate is the org that just authorised. This works whether it's the first time connecting or if the org has been disconnected in the past and is reconnected now.

**Comment by ssta604** [comment]
I understand but it is a bit kludgy and potentially unreliable to use the dates.  Consider the (unlikely) event of two tenents are connecting at the same time.

**Comment by SidneyAllen** [comment]
@ssta604  I appreciate you taking the time to provide this feedback. The answer that @RettBehrens provided is the current way to determine the most recent connection and tenantId.  You also have the option of providing a UI interface where a customer can select which organisation (tenant) they wish to work with.

This question isn't really about the SDK, but about the features of the API.  For this reason  have a uservoice where you can request enhancements to the API https://xero.uservoice.com/forums/5528-xero-accounting-api

**Comment by ssta604** [comment]
Thanks for responding. I see it’s a little more complicated than adding the TenantId.  I’ve taken your suggestion to add selection list.  Thanks again.

**Comment by joshkinabrew** [comment]
We just ran in to this issue in our app. I've submitted a suggestion from that link that @SidneyAllen posted: https://xero.uservoice.com/forums/5528-xero-accounting-api/suggestions/40387714-return-linked-tenant-id-in-the-auth-response -- feel free to upvote if you are having a similar issue.

**Comment by Braemarblue** [comment]
This works

A user can authorise multiple organisations to connect with your app. As you have noted https://api.xero.com/connections will display the organisations that have been authorised, this is based on the access token being used, which in turn is linked to the user.

If you want to find which organisation was added following the authorisation flow you can do so using the authentication_event_id value which is contained within the access token. This can be used when analysing the response to https://api.xero.com/connections as it will match the authEventId value.

**Comment by Yunfeng-Song** [comment]
@Braemarblue  auth event id doesn't change if you reconnect. So it's not very helpful
