### ISSUE TITLE
Missing Purchase Order Attachment Methods

### ISSUE THREAD

**Issue by NeonHorizon** [XeroAPI/xero-php-oauth2#181]
**SDK you're using (please complete the following information):**
 - Version 2.1.6

**Describe the bug**
The following methods appear to be missing from the documentation and do not appear to function:
createPurchaseOrderAttachmentByFileName
getPurchaseOrderAttachmentByFileName
getPurchaseOrderAttachmentById
getPurchaseOrderAttachments

**To Reproduce**
Attempt to use any of the above methods

**Expected behavior**
Functionality identical to the invoice methods listed below but for purchase order attachments:
createInvoiceAttachmentByFileName
getInvoiceAttachmentByFileName
getInvoiceAttachmentById
getInvoiceAttachments

Thanks!

**Comment by SidneyAllen** [comment]
Hey @NeonHorizon 

The docs were out of sync - thanks for flagging that.  Those endpoints are all supported in the current version of the SDK.

Docs are now up. https://github.com/XeroAPI/xero-php-oauth2/blob/master/docs/accounting/Api/AccountingApi.md#createpurchaseorderattachmentbyfilename

**Comment by NeonHorizon** [comment]
Perfect thank you!
