### ISSUE TITLE
bank feeds

### ISSUE THREAD

**Issue by anypoint-aus** [XeroAPI/xero-php-oauth2#184]
I have notice for many months now on this and the node API the README file says coming soon: bank feeds.
I really need these before I can convert my oauth1 to oauth2 and the cut off date is March 2021.
This is the API recommended via the XERO page for PHP.  Is this feature going to be available soon?

**Comment by SidneyAllen** [comment]
Hi @anypoint-aus - our bankfeeds APIs are exclusive to our financial service partners - these are typically banks, credit card companies or other fintechs who originate the transaction data.  

We have not prioritized adding bankfeed support in all of our SDKs as we've only seen demand for use of these APIs in the Java and NodeJS SDKs.

If you fit the description of the type of financial institutions we'd grant access to bank feed APIs, then contact us at api@xero.com to discuss further.
