### ISSUE TITLE
Syncing of Invoices will fail when the BatchPayment details is set to something longer than 18 chars in Xero portal

### ISSUE THREAD

**Issue by suhayls** [XeroAPI/xero-php-oauth2#188]
**SDK you're using (please complete the following information):**
 - Version 2.1.1

**Description**
We are using this package to sync invoices generated from our proprietary application back to xero portal. When a contact in Xero portal has the BatchPayment details set to something with more than 18 characters, this API will return an InvalidArgumentExpression as below:

`invalid length for $details when calling BatchPaymentDetails., must be smaller than or equal to 18. [InvalidArgumentException] (0) at file: /vendor/xeroapi/xero-php-oauth2/lib/Models/Accounting/BatchPaymentDetails.php line: 318`

This is inconsistent with Xero's parameters which allows the BatchPaymentDetails to be larger than 18 Chars. Here is a sample of the detail used and was causing the error:
`EA1405003013625/ NL2014070105 - NL2`

And here is a screenshot from Xero's portal:
![image](https://user-images.githubusercontent.com/863607/100736880-58dd0b80-340e-11eb-9a17-37f7b8c8b46c.png)

**Comment by SidneyAllen** [comment]
@suhayls - thanks for the feedback. This issue was addressed in 2.2.0 release of the SDK

https://github.com/XeroAPI/xero-php-oauth2/releases/tag/2.2.0
