### ISSUE TITLE
Invalid_grant error

### ISSUE THREAD

**Issue by youwe** [XeroAPI/xero-php-oauth2#196]
Does anyone know where this suddenly comes from. 
It was working just fine, but suddenly after some updates the process died.

Fatal error: Uncaught League\OAuth2\Client\Provider\Exception\IdentityProviderException: invalid_grant in /resources/fileshare/releases/20201223173700/htdocs/vendor/league/oauth2-client/src/Provider/GenericProvider.php:222 Stack trace: #0 /resources/fileshare/releases/20201223173700/htdocs/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(628): League\OAuth2\Client\Provider\GenericProvider->checkResponse(Object(GuzzleHttp\Psr7\Response), Array) #1 /resources/fileshare/releases/20201223173700/htdocs/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(537): League\OAuth2\Client\Provider\AbstractProvider->getParsedResponse(Object(GuzzleHttp\Psr7\Request)) #2 /resources/fileshare/releases/20201223173700/htdocs/rest/lib/xero/authorizedResource.php(29): League\OAuth2\Client\Provider\AbstractProvider->getAccessToken(Object(League\OAuth2\Client\Grant\RefreshToken), Array) #3 {main} thrown in /resources/fileshare/releases/20201223173700/htdocs/vendor/league/oauth2-client/src/Provider/GenericProvider.php on line 222

$newAccessToken = $_provider->getAccessToken('refresh_token', [
                'refresh_token' => $this->_storage->getRefreshToken()
            ]);

**Comment by rodjsta** [comment]
Hi @youwe,

It looks like you need to specify the grant_type when requesting the new access token. 

![image](https://user-images.githubusercontent.com/32949856/103028848-4a64b880-45a4-11eb-9172-692b558005b5.jpeg) 

For sanity, I would also check that the app is still connected from within Xero connected apps under settings.

**Comment by youwe** [comment]
Updated the code, but still the same issue.

$newAccessToken = $provider->getAccessToken('refresh_token', [
            'grant_type' => 'refresh_token',
            'refresh_token' => $storage->getRefreshToken()
    ]);

Offline_access was already added. And the app is still connected.

**Comment by rodjsta** [comment]
@youwe try disconnecting the app completely and getting completely fresh tokens through the auth process again. You could then manually trigger the access token expiry and attempt this new code for a new access token.

**Comment by youwe** [comment]
Issue has been resolved. Seems the ID tokens of Xero have changed in format. So now with a base64 encoding the string became much longer and the storage column was not capable in storing the id length.

**Comment by sahilr2050** [comment]
@youwe What size of the column you have set to store the ID tokens?

Did you set TEXT type? or Varchar?

**Comment by rabinacharya** [comment]
@rodjsta I did follow your steps and changed code, disconnected apps, reconnected with new client_id and secret but did not work for me.

Fatal error: Uncaught League\OAuth2\Client\Provider\Exception\IdentityProviderException: invalid_grant in C:\xampp\htdocs\myphp_version\vendor\league\oauth2-client\src\Provider\GenericProvider.php:222 Stack trace: #0 C:\xampp\htdocs\myphp_version\vendor\league\oauth2-client\src\Provider\AbstractProvider.php(628): League\OAuth2\Client\Provider\GenericProvider->checkResponse(Object(GuzzleHttp\Psr7\Response), Array) #1 C:\xampp\htdocs\myphp_version\vendor\league\oauth2-client\src\Provider\AbstractProvider.php(537): League\OAuth2\Client\Provider\AbstractProvider->getParsedResponse(Object(GuzzleHttp\Psr7\Request)) #2 C:\xampp\htdocs\myphp_version\authorizedResource.php(25): League\OAuth2\Client\Provider\AbstractProvider->getAccessToken(Object(League\OAuth2\Client\Grant\RefreshToken), Array) #3 {main} thrown in C:\xampp\htdocs\myphp_version\vendor\league\oauth2-client\src\Provider\GenericProvider.php on line 222

**Comment by roshanpokhrel1994** [comment]
> Issue has been resolved. Seems the ID tokens of Xero have changed in format. So now with a base64 encoding the string became much longer and the storage column was not capable in storing the id length.

How did you resolve this issue ? i have same error
