### ISSUE TITLE
Need a fix for invalid length for $reference

### ISSUE THREAD

**Issue by LWUsira** [XeroAPI/xero-php-oauth2#197]
hi,

I got this following error after trying to get batch payments. 

`Exception when calling BatchPayments invalid length for $reference when calling BatchPayment., must be smaller than or equal to 12.`

And i have found what cause this error, some of references which sent by API has whitespaces.

for a example -:       
`["Reference"]=> string(15) "487 488 489 123"`

**Comment by wobinb** [comment]
This has been updated here: https://github.com/XeroAPI/xero-php-oauth2/blob/bc14b9467bcfe088b4d4f329ad7e75797e412d18/lib/Models/Accounting/BatchPayment.php#L406

Can you confirm you're running the latest version of the SDK?

**Comment by LWUsira** [comment]
2.1 i guess thank you for quick response.
