### ISSUE TITLE
Issues with setBrandingTheme()

### ISSUE THREAD

**Issue by benjaminbowles** [XeroAPI/xero-php-oauth2#198]
I'm trying to update a contact with a different ```BrandingTheme```, but I'm getting no errors and no updates to the contact, what appears to be the problem here? 

All the other setters appear to be working ok on this function, such as ```setName()```.

```
private function xeroAddBrandingTheme(OauthCredentialManager $xeroCredentials, $contact_id, $theme_id)
    {
        $xero = resolve(\XeroAPI\XeroPHP\Api\AccountingApi::class);

        // check Xero
        if ($xeroCredentials->exists()) {
            $contact = new \XeroAPI\XeroPHP\Models\Accounting\Contact;            
            $contact->setBrandingTheme($xero->getBrandingTheme($xeroCredentials->getTenantId(), $theme_id)[0]);

            $xero->updateContact($xeroCredentials->getTenantId(), $contact_id, $contact);

            return $xero;
        }
    }
```

_Corresponding API logs:_
Submit as above: ```1d165ef0-84d8-432e-acc0-47f8c8af034a```
Submit with setName: ```5fbe8c9e-5c13-4d5c-ba7d-5b8595747a66```

**Comment by SidneyAllen** [comment]
Hi @benjaminbowles 

I looked at the API docs and BrandingThemes details for contacts are returned from a GET, but the BrandingTheme property is not listed as an available POST property
https://developer.xero.com/documentation/api/contacts#POST

I did my own test and confirmed the API does not accept the BrandingTheme property on an update.

**Comment by benjaminbowles** [comment]
Where do we submit requests for this to be implemented ?

**Comment by SidneyAllen** [comment]
@benjaminbowles you can upvote this feature on uservoice 👍 

https://xero.uservoice.com/forums/5528-xero-accounting-api/suggestions/5010244-make-the-brandingtheme-for-a-contact-customizable
