### ISSUE TITLE
getContactByContactNumber resulted in 404 Not Found

### ISSUE THREAD

**Issue by graceonce** [XeroAPI/xero-php-oauth2#199]
**SDK you're using (please complete the following information):**
 - Version [^2.3]

**Describe the bug**
I'm trying to GET Contact by ContactNumber but it returns the error _[404] Client error: `GET https://api.xero.com/api.xro/2.0/Contacts/SEA2` resulted in a `404 Not Found` response:\nThe resource you're looking for cannot be found\n_

**To Reproduce**
1. Follow instructions [here](https://github.com/XeroAPI/xero-php-oauth2/blob/master/docs/accounting/Api/AccountingApi.md#getcontactbycontactnumber) and run
2. See error
3. Try changing the value of `$contact_number` to `contact_id` and run
4. Will show correct result

**Expected behavior**
I'm expecting the Contact Model to be returned based on ContactNumber I provide

**Screenshots**
![image](https://user-images.githubusercontent.com/70217373/104049431-edae0280-521f-11eb-8ac3-e88c907bd9b6.png)

**Comment by SidneyAllen** [comment]
@graceonce - thanks for submitting an issue.

Just to confirm, a ContactNumber is not available in Xero's UI, but you can set the ContactNumber through the API.  Once set, you can use the ContactNumber to retrieve that unique contact.

I've tested this using the PHP SDK and it functions as expected.  If you pass an invalid ContactNumber you will receive a 404.

I recommend validating you are using a valid ContactNumber.
