### ISSUE TITLE
Tax Report Types Missing

### ISSUE THREAD

**Issue by gkavaliu** [XeroAPI/xero-php-oauth2#2]
Hello,

There are missing Tax Report Types,

lib/Models/Accounting/TaxRate.php

const REPORT_TAX_TYPE_NONEOUTPUT = 'NONEOUTPUT';
const REPORT_TAX_TYPE_PURCHASESINPUT = 'PURCHASESINPUT';
const REPORT_TAX_TYPE_SALESOUTPUT = 'SALESOUTPUT';

Hope this helps,
Glen

**Comment by SidneyAllen** [comment]
@gkavaliu - Awesome catch!  Thanks - I'll will incorporate into the release today
