### ISSUE TITLE
JWTClaims returning null fields

### ISSUE THREAD

**Issue by netpointneil** [XeroAPI/xero-php-oauth2#20]
Some of the fields do not appear to be working for me:

```
    $userDetails = [
      'sub' => $xeroUser->getSub(),
      'iss' => $xeroUser->getIss(),
      'aud' => $xeroUser->getAud(),
      'exp' => $xeroUser->getExp(),
      'iat' => $xeroUser->getIat(),
      'email' => $xeroUser->getEmail(),
      'firstName' => $xeroUser->getGivenName(),
      'familyName' => $xeroUser->getFamilyName(),
      'username' => $xeroUser->getPreferredUsername(),
      'sessionId' => $xeroUser->getGlobalSessionId(),
      'authTime' => $xeroUser->getAuthTime()
    ];

```
produces the following:

```
{
    "sub": null,
    "iss": "https://identity.xero.com",
    "aud": null,
    "exp": null,
    "iat": null,
    "email": "neil@netpoint.group",
    "firstName": "Neil",
    "familyName": "Wilkinson",
    "username": "neil@netpoint.group",
    "sessionId": "[DELETED]",
    "authTime": 1576711561
}
```

Expiry time is the only really important one for me.

Thanks in advance for investigating.

**Comment by SidneyAllen** [comment]
Hi @netpointneil 

Release version 1.0.8 with updates to the decoding of the JWT.  Got most values being returned including expiration - but for some reason still struggled to get the IAT and AUD values properly returned after decoding.  Stumped, so if anyone can figure out what I'm doing wrong, would appreciate a PR.

Give the latest version a go and let me know if that works for you.

**Comment by netpointneil** [comment]
Hey @SidneyAllen I'm getting problems when trying 1.08 or 1.10.

Code:
```
$idToken = $accessToken->getValues()["id_token"];
error_log("ID Token:");
error_log(json_encode($idToken));
$jwt = new \XeroAPI\XeroPHP\JWTClaims($idToken);
if ($jwt->decode()) {
```
produces this in the logs:

![image](https://user-images.githubusercontent.com/57199356/72040533-f0b89f00-32fc-11ea-8259-c0675336f098.png)

The domain error causes the code to exit.

Rolling back to 1.0.6 worked, 1.0.7, 1.0.8 and 1.0.10 all produce the same error above.
