### ISSUE TITLE
Credit Note Response Contains Empty LineItemID

### ISSUE THREAD

**Issue by Danbardo** [XeroAPI/xero-php-oauth2#202]
**SDK you're using (please complete the following information):**
Latest

**Describe the bug**
When I create a credit note the object which is returned in the POST response contains all the LineItem's, but all with empty LineItemId's.

I'm not sure if this is a fault of the SDK itself, something I am missing with how Credit Notes work, or a flaw in the servers response.

**To Reproduce**
Create a CreditNote object, post it and print_r the response.

**Expected behavior**
I expected the LineItemId's to be generated by the Xero server and returned in the response. Similar to how Invoice's work. 

**Screenshots**
Here is a snippet from the LineItems dump:
Array ( [0] => XeroAPI\XeroPHP\Models\Accounting\LineItem Object ( [container:protected] => Array ( [line_item_id] => [description] => Example Desc [quantity] => 1 ......

**Comment by Danbardo** [comment]
Also, why doesn't the API allow us to filter out CreditNotes by createdByMyApp? Is there any way to filter out credit notes that aren't generated by the SDK?

**Comment by SidneyAllen** [comment]
Hi @Danbardo - Thanks for the feedback.

Regarding the line_item_id not being returned with CreditNotes. This is a known issue with the API and therefore can't be addressed in client SDK. I have followed up with our API team to see if we can get it addressed in the future.

createdByMyApp is not supported by the API for CreditNotes.  But I understand your reasoning as Invoices are similar to credit notes and do offer this filter.  I'll raise this with the API team for consideration as well.

I do want to set your expectations properly.  We receive a significant number of requests for our API team and they prioritize these requests accordingly.  

I'll be closing this issue as it's not directly related to the SDK.

**Comment by Danbardo** [comment]
Thanks @SidneyAllen ,
Is there any way that I can contact the API team? I posted here as I could not find their contact details.
Thanks,
Daniel

**Comment by SidneyAllen** [comment]
Hi @Danbardo 

On this issue, I have communicated it directly to the API team.  As a developer evangelist, part of my job is to advocate on behalf of the developer community.

We do have a user voice forum where developers can suggest feature improvements and upvote ideas.  This board is owned by the API team. https://xero.uservoice.com/forums/5528-xero-accounting-api

If you have support questions, you can email Xero's API support team at api@xero.com
