### ISSUE TITLE
Cannot redefine class constant 

### ISSUE THREAD

**Issue by DeweyOx** [XeroAPI/xero-php-oauth2#21]
Fatal error: Cannot redefine class constant XeroAPI\XeroPHP\Models\Accounting\TaxRate::REPORT_TAX_TYPE_EXEMPTCAPITAL in 
/vendor/xeroapi/xero-php-oauth2/lib/Models/Accounting/TaxRate.php on line 241

It's defined already on line 228. Deleting it is all that's needed.

**Comment by SidneyAllen** [comment]
Hi @DeweyOx 

Thanks for the feedback. we've released a fix in version 1.0.6 yesterday.
