### ISSUE TITLE
Composer dependency error thrown when migrating to oAuth2.0 using xero-php-oauth2

### ISSUE THREAD

**Issue by ContactPointIT** [XeroAPI/xero-php-oauth2#215]
Hi,

We need to migrate a PHP project from Xero oAuth1.0 to oAuth2.0. As per the docs, I went ahead and installed the xeroapi/xero-php-oauth2 package using composer. 

I have followed exactly the steps provided by xeroapi/xero-php-oauth2 documentation and tried the sample code provided ( https://github.com/XeroAPI/php-oauth2-example ), with a callback.php. But when I try to run the callback.php, it throws a **Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.2.5"** error.

Although my server php version is 7.3.24 and the package requires PHP 5.6 and later, it throws the above mentioned error. My app configuration with Xero is correct, as I have confirmed this with the Xero team. 

I am not sure what I am doing wrong here but this is of high priority to us at the moment. Any insights or clarification in this regard would be of great help. 

Thanks...

**Comment by SidneyAllen** [comment]
Hi @ContactPointIT - thanks for reaching out.

This doesn't appear to be an issue with the SDK but with server environment.  I would do some searching to see what other PHP developer recommend to address this.

I found this stackoverflow article that offers some guidance.
https://stackoverflow.com/questions/65339404/composer-detected-issues-in-your-platform-your-composer-dependencies-require-a

**Comment by SidneyAllen** [comment]
@ContactPointIT - if you have anything more to share on this issue that might help other developers please feel free to comment.  I'll close it for now.
