### ISSUE TITLE
UK Payroll SalaryAndWage does not support Hourly PaymentType

### ISSUE THREAD

**Issue by aarangara** [XeroAPI/xero-php-oauth2#221]
**SDK you're using (please complete the following information):**
 - Version 2.5.1

**Describe the bug**
For an **UK PAYROLL**, I am trying to create an Hourly SalaryAndWage object for the Employement of an Employee, but it fails because the only supported payment type is "Salary". 

Is there any specific reason why "Hourly" payment type is not supported?

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPaymentTypeAllowableValues()
    {
        return [
            self::PAYMENT_TYPE_SALARY,
        ];
    }

**Comment by SidneyAllen** [comment]
@aarangara Thanks for the feedback. 

This is corrected in version 2.5.2
https://github.com/XeroAPI/xero-php-oauth2/releases/tag/2.5.2
