### ISSUE TITLE
Multiple where statements cause errors

### ISSUE THREAD

**Issue by DeweyOx** [XeroAPI/xero-php-oauth2#23]
Trying to get tax rates for sales that are active, so I'm passing in two where clauses like:

            $where = array(
                'Name.Contains("Sales")',
                'Status=="ACTIVE"'
            );
            $response = $this->xero->getTaxRates($tenant, $where);

Each one works independently, however together, they cause 

            {
              "ErrorNumber": 16,
              "Type": "QueryParseException",
              "Message": "Syntax error"
            }

It looks as if the resultant comma is being urlencoded. Might that be the issue?

**Comment by SidneyAllen** [comment]
Hi @DeweyOx,

Just tested this and the following where clause works.

$where = 'Status=="ACTIVE" && Name.Contains("Sales")';
