### ISSUE TITLE
Not working in PHP 5.6

### ISSUE THREAD

**Issue by mhasannasir** [XeroAPI/xero-php-oauth2#233]
**SDK you're using (please complete the following information):**
 - Version Latest Stable Version 2.5.4
 - PHP 5.6.40

**Describe the bug**
While installing this library its giving me error for PHP 7, See Screenshot.
Where it should work on php 5.6 as well. 

**To Reproduce**
- Get fresh copy of Laravel 4
- Composer require this build and it gives error

**Expected behavior**
It should work on PHP 5.6

**Screenshots**
![image](https://user-images.githubusercontent.com/8911539/119119327-8a8d7180-ba44-11eb-8ad1-730841bb7747.png)

**Additional context**

**Comment by thomasedwards** [comment]
PHP 5.6 reached its end of life on the 31st December 2018.

**Comment by RettBehrens** [comment]
As pointed out above, PHP 5.6 reached end of life December 31st 2018. At this time we don't intend to maintain support for PHP 5.6
