### ISSUE TITLE
When creating a new Contact (createContact), setAddresses & setPhones are ignored

### ISSUE THREAD

**Issue by DeweyOx** [XeroAPI/xero-php-oauth2#24]
Using:

            $contact = new XeroAPI\XeroPHP\Models\Accounting\Contact;
            $person = new XeroAPI\XeroPHP\Models\Accounting\ContactPerson;
            $address = new XeroAPI\XeroPHP\Models\Accounting\Address;
            $terms = new XeroAPI\XeroPHP\Models\Accounting\PaymentTerm;
            $sales = new XeroAPI\XeroPHP\Models\Accounting\Bill;

            $person
                ->setFirstName($data['first'])
                ->setLastName($data['last'])
                ->setEmailAddress($data['email']);

            $address
                ->setAddressLine1($data['address'])
                ->setCity($data['city'])
                ->setRegion($data['state'])
                ->setPostalCode($data['postal']);

            $sales
                ->setDay(30)
                ->setType(XeroAPI\XeroPHP\Models\Accounting\PaymentTermType::DAYSAFTERBILLDATE);

            $terms
                ->setSales($sales);

            $contact
                ->setFirstName($data['first'])
                ->setLastName($data['last'])
                ->setEmailAddress($data['email'])
                ->setName(html_entity_decode($data['name']))
                ->setAccountNumber($data['account'])
                ->setContactPersons(array($person))
                ->setPaymentTerms($terms)
                ->setAddresses(array($address));

            $resp = $this->xero->createContact($tenant, $contact);

Creates a customer nicely, however the address or phone (not included here) is not saved. Any idea why that would be the case?

It seems the serialization is ignoring these elements when they are passed in an array.

**Comment by TapanDerasari** [comment]
@DeweyOx ,

Yes, the Same happened to me.
 I found a workaround, You can create your own array and pass it to setAddresses(). 

Ex:
```
$address = array(array(
            'AddressType' => 'POBOX',
            'AddressLine1' =>'P O Box 123',
            'City' => 'Sydney',
            'PostalCode' => '2000',
            'Country' => 'Australia',
            'AttentionTo' =>'Andrea',
        ));

$contact
            ->setFirstName($data['first'])
            ->setLastName($data['last'])
            ->setEmailAddress($data['email'])
            ->setName(html_entity_decode($data['name']))
            ->setAccountNumber($data['account'])
            ->setContactPersons(array($person))
            ->setPaymentTerms($terms)
            ->setAddresses($address);
```

This is working fine for me.

**Comment by SidneyAllen** [comment]
Hi @DeweyOx ... @TapanDerasari  is correct.

For properties which are arrays, you'll need to pass the object to the array and then set the value of the property to that array.

Below is an example with an array of ContactPersons on a Contact.  If Tapan's syntax works and is to you liking you can use that approach as well.

$person = new XeroAPI\XeroPHP\Models\Accounting\ContactPerson;
$person->setFirstName("John")
	->setLastName("Smith")
	->setEmailAddress("john.smith@24locks.com")
	->setIncludeInEmails(true);

$persons = [];		
array_push($persons, $person);

$contact = new XeroAPI\XeroPHP\Models\Accounting\Contact;
$contact->setName('FooBar' . $this->getRandNum())
	->setFirstName("Foo" . $this->getRandNum())
	->setLastName("Bar" . $this->getRandNum())
	->setEmailAddress("ben.bowden@24locks.com")
	->setContactPersons($persons);

**Comment by githubjonny** [comment]
Hi, I'm having a similar issue to the above.

I've used:

```
////////////////////////////////////////////////////////////////////////////////
//[add a contact]
////////////////////////////////////////////////////////////////////////////////



            $address = new XeroAPI\XeroPHP\Models\Accounting\Address;
            $address
            ->setAddressLine1('1 test street')
            ->setAddressLine2('2 test street line')
            ->setCity('CityName');
            $address_array = [];
            array_push($address_array, $address);

            var_dump($address_array);
            echo "<hr>";

            $contact = new XeroAPI\XeroPHP\Models\Accounting\Contact;
            $contact->setName($setFirstName . " ". $setLastName . " (#" .$CustomerID . ")")
                ->setFirstName($setFirstName)
                ->setLastName($setLastName)
                ->setEmailAddress($setEmailAddress)
                ->setContactNumber($CustomerID)
                ->setAddresses($address_array)
                
                ;
            
            $arr_contacts = [];
            array_push($arr_contacts, $contact);
            
            $contacts = new XeroAPI\XeroPHP\Models\Accounting\Contacts;
            $contacts->setContacts($arr_contacts);

            $apiResponse = $apiInstance->createContacts($xeroTenantId,$contacts);
            
            $message = 'New Contact Name: ' . $apiResponse->getContacts()[0]->getName() .'<hr>' . $apiResponse->getContacts()[0]->getContactId() ;
            
            echo "<hr>";
            echo $message;
            echo "<hr>";

//[/add a contact]
```

but this doesn't add the address to the customers account.

Looking at the output, I appears like the address is being added but then overwritten by blank details. I'm assuming this means I have the array wrong and its writing a blank array over but I can see why.
