### ISSUE TITLE
IsDiscounted field always false when getInvoices summaryOnly true

### ISSUE THREAD

**Issue by Youdaman** [XeroAPI/xero-php-oauth2#241]
**SDK you're using (please complete the following information):**
 - Version 2.6.0

**Describe the bug**
When summaryOnly for getInvoices is set to false the IsDiscounted contains true when a line item has a discount applied.

When the summaryOnly  is set to true, IsDiscounted always returns false regardless of whether there is a discount or not.

**To Reproduce**
1. add a discount to a line item in Xero
2. call getInvoices with summaryOnly set to true
3. look at the returned IsDiscounted field

**Expected behavior**
IsDiscounted should contain a value of true.

**Comment by Youdaman** [comment]
Also, there is no TotalDiscount field as suggested by the docs.

**Comment by SerKnight** [comment]
Hey @Youdaman - yes. This is a result of doing a GET for all invoices not fetching the line items. It would seem that that derives the boolean that tells if an invoice has discounts or not. I will flag this as an API bug but considering it isn't unique to PHP I am closing this issue. I will report back to you when the team plans to address this nuance.

### Get ALL
![Screen Shot 2021-07-22 at 1 52 13 PM](https://user-images.githubusercontent.com/2935387/126701094-4320b70d-f332-45e2-a63d-9fd03098c962.png)

### Get Single
![Screen Shot 2021-07-22 at 1 51 50 PM](https://user-images.githubusercontent.com/2935387/126701056-1f0722bd-6787-4837-aa5e-39c21939684f.png)


---

### Create

![Screen Shot 2021-07-22 at 1 50 50 PM](https://user-images.githubusercontent.com/2935387/126700932-c9e14b3c-9469-4ff0-95eb-93184a757403.png)

**Comment by Youdaman** [comment]
Any update on this nuance @SerKnight ? As you mentioned it's not unique to PHP and I've also struck it using Node.

**Comment by SerKnight** [comment]
cc @RettBehrens
