### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by mikkyluchi** [XeroAPI/xero-php-oauth2#25]
Hello,
I followed your tutorials to implement the sample code but when i try to connect i get error 500 error

**Comment by rodjsta** [comment]
make sure your callback url is set correctly

**Comment by SidneyAllen** [comment]
@mikkyluchi 

I found a bug in some of the sample code and have cleaned it up as well as polished the README overall.  Give it a go and make sure your client id, secret and redirectURI are set properly in the authorize.php, callback.php and authorizedResource.php files.

Please use version 1.0.8 of the sdk.
