### ISSUE TITLE
TaxRate Import - InvalidArgumentException

### ISSUE THREAD

**Issue by arunjamesk** [XeroAPI/xero-php-oauth2#26]
Upon importing the tax rates from XERO, I'm getting the following error.

Exception 'InvalidArgumentException' with message 'Invalid value for 'report_tax_type', must be one of 'OUTPUT',
'INPUT', 'EXEMPTOUTPUT', 'INPUTTAXED', 'BASEXCLUDED', 'EXEMPTEXPENSES', 'EXEMPTINPUT', 'ECOUTPUT', 'ECOUTPUTSERVICES',
'ECINPUT', 'ECACQUISITIONS', 'CAPITALSALESOUTPUT', 'CAPITALEXPENSESINPUT', 'MOSSSALES', 'NONE', 'GSTONIMPORTS''

in vendor/xeroapi/xero-php-oauth2/lib/Models/Accounting/TaxRate.php:478
vendor/xeroapi/xero-php-oauth2/lib/AccountingObjectSerializer.php(351):
XeroAPI\XeroPHP\Models\Accounting\TaxRate->setReportTaxType('EXEMPTCAPITAL')

When I add the following constants to vendor/xeroapi/xero-php-oauth2/lib/Models/Accounting/TaxRate.php  file, it works.

1. EXEMPTCAPITAL
2. EXEMPTEXPORT
3. GSTONCAPITALIMPORTS 

Is there a way you can add a fix to the repository ?

Thanks

**Comment by wobinb** [comment]
As with all our current SDKs this is auto generated from our OpenAPI specification. I can see that EXEMPTCAPITAL and EXEMPTEXPORT are currently included, as such they'll filter through the next time it is generated. 

I don't however see GSTONCAPITALIMPORTS only GSTONCAPIMPORTS. Can you confirm which sort of organisation you are seeing this on (regional edition, and or demo)?

**Comment by SidneyAllen** [comment]
@arunjamesk 

I've released version 1.0.8 of the SDK.  Should have all the enums for ReportTaxType.  let me know if you have any further issues with these.
