### ISSUE TITLE
Documentation does not list how to use BankAccount AccountID or multiple filters

### ISSUE THREAD

**Issue by zoe-edwards** [XeroAPI/xero-php-oauth2#260]
**SDK you're using:**
 - Version 2.9.0

**Describe the bug**
The documentation simply say “use filters” and gives an example of using a Status filter. It does not say how to use multiple filters or how to use nested filters.

**To Reproduce**
1. Go to https://xeroapi.github.io/xero-php-oauth2/docs/v2/accounting/index.html#api-Accounting-getBankTransactions
2. View this code:

```
$where = "Status=="' . XeroAPI\XeroPHP\Models\Accounting\BankTransaction::STATUS_AUTHORISED . '"";
```

Note that this is not actually valid PHP code.

**Expected behavior**
The documenation to display accurate PHP code, that says how to use filters.

**Comment by thomasedwards** [comment]
Got half-way, this is how you do nested filters:

    BankAccount.AccountID==GUID("A728B055-XXX-XXX-XXXX-BF03A161DBD7")

**Comment by RettBehrens** [comment]
@zoe-edwards you are correct re: nested filter as above.

It also looks like the quotes got switched around in the generated docs example.

Below is code from the sample app demonstrating how to use multiple filters using the `AND` filter operator and PHP string concatenation.

`$where = 'Status=="' . \XeroAPI\XeroPHP\Models\Accounting\Account::STATUS_ACTIVE .'" AND Type=="' .  \XeroAPI\XeroPHP\Models\Accounting\AccountType::FIXED . '"';`

I'm working on an update to the generated language docs and will include correcting the example on the next build

**Comment by zoe-edwards** [comment]
Thank you!
