### ISSUE TITLE
Xero Practice Manager API

### ISSUE THREAD

**Issue by ltrtuan** [XeroAPI/xero-php-oauth2#261]
Hi
Do your package have Xero Practice Manager API https://developer.xero.com/documentation/api/practice-manager/overview-practice-manager/#overview
Can i use your package to implement Practice Manager API? i know my app need to be approved first.

**Comment by RettBehrens** [comment]
Hi @ltrtuan 

While this package supports the following APIs:
- Accounting
- AppStore
- Assets
- Files
- Finance
- Identity
- PayrollAU
- PayrollNZ
- PayrollUK
- Project

It does not support Xero Practice Manager or WorkflowMax APIs
