### ISSUE TITLE
Invalid Branding Theme ID prevents invoice creation via API

### ISSUE THREAD

**Issue by faisal-alvi** [XeroAPI/xero-php-oauth2#267]
**Describe the bug**

I am using https://woocommerce.com/products/xero/ and when I set a branding theme to link with my invoices generated with online orders, WooCommerce Order places successfully but Xero invoice is not created at Xero dashboard, it is because the Branding Theme ID is deleted from the Xero (by me) which was used at my WordPress site.

**Expected behavior**
If a branding theme is invalid or it no longer exists, invoice creation should not be prevented, instead, an API should be smart enough and use a default theme template.

This fix should not only be added in the SDK but it should be added in [plain API](https://developer.xero.com/documentation/api/accounting/invoices/#post-invoices) calls so all users get benefit from it.

**Comment by RettBehrens** [comment]
Hey @faisal-alvi closing as this isn't an SDK issue per se. Please consider opening a support case with api@xero.com

**Comment by faisal-alvi** [comment]
okay, thanks you.
