### ISSUE TITLE
Unknown tracking details. A Tracking Category did not match a known Active TrackingCategory for purchase orders

### ISSUE THREAD

**Issue by shorif2000** [XeroAPI/xero-php-oauth2#268]
**SDK you're using (please complete the following information):**
 - Version 2.9

**Describe the bug**
Adding a tracking category and option for each line item in a purchase order via the api  in php does not work. 

**To Reproduce**
1. create tracking category 'project'
2. create an option for the category
3. set these on the line item for purchase order

```
$tc = new LineItemTracking();
                    $tc->setTrackingCategoryId($trackingCategoryId);
                    $tc->setTrackingOptionId($trackingOptionId);

                    $lineItem->setTracking([$tc]);
```

**Expected behavior**
Create a purchase order with tracking

**Actual behaviour**

It errors with `Unknown tracking details. A Tracking Category did not match a known Active TrackingCategory`. The same steps work for Invoices and Credit Notes

**Comment by rodjsta** [comment]
@shorif2000, I'm pretty sure you'll find that you need to use the name of the tracking category rather than the ID. 

It's very silly, but that's what I discovered when trying to add tracking categories to line items.

**Comment by shorif2000** [comment]
> @shorif2000, I'm pretty sure you'll find that you need to use the name of the tracking category rather than the ID.
> 
> It's very silly, but that's what I discovered when trying to add tracking categories to line items.

How do you set the name because the function clearly says `setTrackingCategoryId` and `setTrackingOptionId`
