### ISSUE TITLE
Installation fails due to incompatibility with already-installed firebase/php-jwt

### ISSUE THREAD

**Issue by danhobbs75** [XeroAPI/xero-php-oauth2#278]
Attempting to install latest version

**Describe the bug**
Installation fails because it depends on firebase/php-jwt ^5.0, but I am already using a later version of that (6.1.2).

**To Reproduce**
1. Install firebase/php-jwt (composer require firebase/php-jwt)
2. Install xeroapi/xero-php-oauth2 (composer require xeroapi/xero-php-oauth2)
3. See error below

**Expected behavior**
Installation expected.

**Screenshots**
Not a screenshot, but here is the text shown by composer:

Info from https://repo.packagist.org: #StandWithUkraine
Using version ^2.13 for xeroapi/xero-php-oauth2
./composer.json has been updated
Running composer update xeroapi/xero-php-oauth2
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires xeroapi/xero-php-oauth2 ^2.13 -> satisfiable by xeroapi/xero-php-oauth2[2.13.0].
    - xeroapi/xero-php-oauth2 2.13.0 requires firebase/php-jwt ^5.0 -> found firebase/php-jwt[v5.0.0, ..., v5.5.1] but it conflicts with your root composer.json require (6.1.2).

**Additional context**
There is a small API change in firebase/php-jwt which means the dependency must also move up and it can't be backwards compatible once you make that change.

I'm going to look to see if I can do the code change for you but if this is something you already know about it might be easier for you to do it.

**Comment by RettBehrens** [comment]
looking to resolve with #281
