### ISSUE TITLE
Bug in setting SummarizeErrors

### ISSUE THREAD

**Issue by griffta** [XeroAPI/xero-php-oauth2#28]
I have been trying to create multiple contacts and I need the ID of all created contacts as any validation errors relating to bad entities that din't create. I understand that to get this functionality, requests should be sent with the SummarizeErrors query parameter set to false. I can see that there is some logic around this in AccountinApi.php, but it doesn't work. Setting $summarize_errors to false does causes the query paramter to be sent as 'SummarizeErrors=' rather than 'SummarizeErrors=false'

The issue relates to line 5809 in AccountinApi.php. If I hard code the value to false, all works as expected.

**Comment by SidneyAllen** [comment]
@griffta - Thank you very much!  Great catch.  the boolean wasn't being properly appended to the query string.

I've tested this out and added sample code in the README.
