### ISSUE TITLE
get invoice as pdf show me error

### ISSUE THREAD

**Issue by izhar77** [XeroAPI/xero-php-oauth2#282]
#error

Warning: settype(): Invalid type in D:\xampp\htdocs\xero\vendor\xeroapi\xero-php-oauth2\lib\AccountingObjectSerializer.php on line 312

#code
$invoiceID = "15b39203-5567-4244-8e08-f6401e5f7e50";
      $unitdp = 4;
      try {
        $result = $accountingApi->getInvoiceAsPdf($xeroTenantId, $invoiceID,$unitdp);
      } catch (Exception $e) {
        echo 'Exception when calling AccountingApi->getInvoiceAsPdf: ', $e->getMessage(), PHP_EOL;
      }

**Comment by RettBehrens** [comment]
looking to resolve with #281

**Comment by dcodegroup** [comment]
I have this same issue.

**Comment by timothystringer** [comment]
Same issue

**Comment by lionslair** [comment]
The rollback resolved it for me

**Comment by RettBehrens** [comment]
closing resolved
