### ISSUE TITLE
authorizedResource.php example file appears to have errors

### ISSUE THREAD

**Issue by rodjsta** [XeroAPI/xero-php-oauth2#29]
When requesting the new access token, I was receiving 'invalid_grant' errors. To resolve I added 

`'grant_type' => 'refresh_token'`

into this array:
`$newAccessToken = $provider->getAccessToken('refresh_token', [
      'refresh_token' => $storage->getRefreshToken()
    ]);`

Also needed to supply the id_token when setting the new token:
`$newAccessToken->getValues()["id_token"]`
into:

`// Save my token, expiration and refresh token
   $storage->setToken(
      $newAccessToken->getToken(),
      $newAccessToken->getExpires(), 
      $xeroTenantId,
      $newAccessToken->getRefreshToken()
    );`

**Comment by SidneyAllen** [comment]
@rodjsta - good catch.  I missed adding a 5th param to the storage token method.

I've updated and tested the sample code in the README.  Cheers.

**Comment by SaxPlayer** [comment]
I’m also receiving invalid_grant errors (see @rodjsta update below). My process looks identical to that apart from the line reference “id_token” as I can’t see where that should go.

Latest update via composer installed.

Everything fine until token expires, then get error:

Fatal error: Uncaught League\OAuth2\Client\Provider\Exception\IdentityProviderException: invalid_grant in /home/sandbox/public_html/vendor/league/oauth2-client/src/Provider/GenericProvider.php:222 Stack trace: #0 /home/sandbox/public_html/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(628): League\OAuth2\Client\Provider\GenericProvider->checkResponse(Object(GuzzleHttp\Psr7\Response), Array) #1 /home/sandbox/public_html/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(537): League\OAuth2\Client\Provider\AbstractProvider->getParsedResponse(Object(GuzzleHttp\Psr7\Request)) #2 /home/sandbox/public_html/v3/inc/xeroinit.php(26): League\OAuth2\Client\Provider\AbstractProvider->getAccessToken(Object(League\OAuth2\Client\Grant\RefreshToken), Array) #3 /home/sandbox/public_html/v3/edit-customer.php(7): include_once('/home/sandbox...') #4 {main} thrown in /home/sandbox/public_html/vendor/league/oauth2-client/src/Provider/GenericProvider.php on line 222

The error is being thrown when my code gets to here:

$newAccessToken = $provider->getAccessToken('refresh_token', [
  'refresh_token' => $storage->getRefreshToken()
]);

I can post more code if needed to help.

**Comment by rodjsta** [comment]
![image](https://user-images.githubusercontent.com/32949856/73442036-c9a33980-439f-11ea-8cdd-bd9b4ec85317.png)

**Comment by SaxPlayer** [comment]
Throws:

Fatal error: Uncaught League\OAuth2\Client\Provider\Exception\IdentityProviderException: invalid_grant in /home/sandbox/public_html/vendor/league/oauth2-client/src/Provider/GenericProvider.php:222 Stack trace: #0 /home/sandbox/public_html/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(628): League\OAuth2\Client\Provider\GenericProvider->checkResponse(Object(GuzzleHttp\Psr7\Response), Array) #1 /home/sandbox/public_html/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(537): League\OAuth2\Client\Provider\AbstractProvider->getParsedResponse(Object(GuzzleHttp\Psr7\Request)) #2 /home/sandbox/public_html/v3/inc/init.php(23): League\OAuth2\Client\Provider\AbstractProvider->getAccessToken(Object(League\OAuth2\Client\Grant\RefreshToken), Array) #3 /home/sandbox/public_html/v3/edit-customer.php(7): include_once('/home/sandbox...') #4 {main} thrown in /home/sandbox/public_html/vendor/league/oauth2-client/src/Provider/GenericProvider.php on line 222

**Comment by SaxPlayer** [comment]
Ooops. Included my secret in the screenshot. Schoolboy error. Have generated a new one!

**Comment by rodjsta** [comment]
The docs (https://developer.xero.com/documentation/oauth2/troubleshooting) say that an invalid_grant could be for many reasons.

Best to disconnect your app (https://apps.xero.com/au/connected) and try again with the new code that I screenshotted above.

From memory, even though I changed the code I still got the error. Had to disconnect and connect/authorise again with the new code.

**Comment by SaxPlayer** [comment]
@rodjsta Taking the additional step of disconnecting the app and reconnecting it again appears to have solved the problem. Thanks for the tip! This one has had me tearing my hair out for days!
