### ISSUE TITLE
Composer update command not updating this xeroapi

### ISSUE THREAD

**Issue by jagguy** [XeroAPI/xero-php-oauth2#300]
**SDK you're using (please complete the following information):**
 - Version 2.1.7

**Describe the bug**
the update seems to work with error but it says no files to install and nothing is updated
composer update xeroapi/xero-php-oauth2

**To Reproduce**
go to the vendor folder 
go to the xeroapi folder
in the command line type the below. it runs without error but no files to update on an 2021 version of xero

composer update xeroapi/xero-php-oauth2

this is the json file

{
    "name": "xeroapi/xero-php-oauth2",
    "description": "Xero official PHP SDK for oAuth2 generated with OpenAPI spec 3",
    "keywords": [
        "openapispec",
        "xero",
        "php",
        "sdk",
        "rest",
        "api"
    ],
    "homepage": "https://github.com/xeroapi/xero-php-oauth2",
    "license": "MIT",
    "authors": [
        {
            "name": "Xero API Team",
            "homepage": "https://developer.xero.com"
        }
    ],
    "require": {
        "php": ">=5.6",
        "ext-curl": "*",
        "ext-json": "*",
        "ext-mbstring": "*",
        "guzzlehttp/guzzle": "^6.2 | ^7.0",
        "league/oauth2-client": "^2.5.0",
        "firebase/php-jwt": "^5.0"
    },
    "require-dev": {
        "phpunit/phpunit": "^4.8",
        "squizlabs/php_codesniffer": "~2.6",
        "friendsofphp/php-cs-fixer": "~2.12"
    },
    "autoload": {
        "psr-4": { "XeroAPI\\XeroPHP\\" : "lib/" }
    },
    "autoload-dev": {
        "psr-4": { "XeroAPI\\XeroPHP\\" : "test/" }
    }
}

**Comment by pumpkinball** [comment]
Hey @jagguy , we recommend you install one of the sample Apps (https://github.com/XeroAPI/xero-php-oauth2#sample-applications) , which contain a composer.json file, and then run composer update in the sample app.
 
This will then install the dependency xeroapi/xero-php-oauth2 at whatever version is referenced. 
See here - https://github.com/XeroAPI/xero-php-oauth2-app/blob/master/composer.json
and here for the full app -
https://github.com/XeroAPI/xero-php-oauth2-app

**Comment by pumpkinball** [comment]
Hi @jagguy haven't had an update from you, so I'm closing this out. Do come back if you still have an issue.
