### ISSUE TITLE
Access Denied to https://identity.xero.com/connect/token

### ISSUE THREAD

**Issue by surbhi-brightness** [XeroAPI/xero-php-oauth2#302]
**SDK you're using (please complete the following information):**
-  "xeroapi/xero-php-oauth2": "^2.17"

**Describe the bug**
- I am getting access denied s=issue while using "https://identity.xero.com/connect/token" for authorization.
It was working perfectly before 2 days. Today my _trial app got expired and I have created new app_ and now I am getting this error **"Invalid response received from Authorization Server. Expected JSON."**

**Expected behavior**
- API should redirect once get authorization

**Screenshots**
![image](https://user-images.githubusercontent.com/86059522/199022986-1ef6c240-b90e-4852-abd2-5b0f5c6ec4a9.png)

**Comment by pumpkinball** [comment]
Hi @surbhi-brightness can I check please, can you run the request via Insomnia or Postman ok, using your existing clientId and secret?
https://developer.xero.com/documentation/guides/oauth2/auth-flow

**Comment by Aplear** [comment]
The same issue

**Comment by Aplear** [comment]
The same with postman
![Xero-GrandType_AuthCode](https://user-images.githubusercontent.com/5145711/199244764-e5d80632-5a48-40df-b8c7-3d0d6dc03f55.png)

**Comment by pumpkinball** [comment]
Thanks @Aplear, it looks like it could be an issue related to ngrok. 
Are you using ngrok on your development environment?
And @surbhi-brightness can you confirm you are also getting the error whilst using ngrok?

**Comment by surbhi-brightness** [comment]
@pumpkinball Yes!

I am using ngrok and getting issue with ngrok only. Before 2 days it was working perfectly with ngrok.

**Comment by surbhi-brightness** [comment]
@pumpkinball Do you have any idea about this? 
It should work as it was working before

**Comment by pumpkinball** [comment]
We have raised it internally, and I will keep you posted on the progress :)
It may be a day or two.

**Comment by Aplear** [comment]
Hi @pumpkinball  All has been fine a week ago.

**Comment by Aplear** [comment]
It dose not work with ngrok

**Comment by RettBehrens** [comment]
Could you try [localtunnel](https://theboroer.github.io/localtunnel-www/) as an alternative to ngrok?

**Comment by pumpkinball** [comment]
Hi @Aplear please can you log this issue now with api@xero.com and they should be able to jump on it.
