### ISSUE TITLE
JWTClaims.php throwing errors

### ISSUE THREAD

**Issue by edwardinchains** [XeroAPI/xero-php-oauth2#31]
I have attempted to install and use the xero-php-oauth2 on multiple instances,

Each time I do, I follow the install instructions to the letter - my application gets to the point where the user approves application accesss, when the user is redirected back the following error keeps displaying:

`Notice: Undefined offset: 1 in C:\inetpub\wwwroot\myApp\vendor\xeroapi\xero-php-oauth2\lib\JWTClaims.php on line 29

Notice: Undefined offset: 2 in C:\inetpub\wwwroot\myApp\vendor\xeroapi\xero-php-oauth2\lib\JWTClaims.php on line 29

Fatal error: Uncaught DomainException: Syntax error, malformed JSON in C:\inetpub\wwwroot\myApp\vendor\firebase\php-jwt\src\JWT.php:358 Stack trace: #0 C:\inetpub\wwwroot\myApp\vendor\firebase\php-jwt\src\JWT.php(286): Firebase\JWT\JWT::handleJsonError(4) #1 C:\inetpub\wwwroot\myApp\vendor\xeroapi\xero-php-oauth2\lib\JWTClaims.php(30): Firebase\JWT\JWT::jsonDecode('', true) #2 C:\inetpub\wwwroot\myApp\callback.php(46): XeroAPI\XeroPHP\JWTClaims->decode() #3 {main} thrown in C:\inetpub\wwwroot\myApp\vendor\firebase\php-jwt\src\JWT.php on line 358`

This occurs regardless of what machine I run this or any other variation of the application I have created - any suggestions would be great!

**Comment by itboffins** [comment]
Are you using the callback.php code here: https://github.com/XeroAPI/xero-php-oauth2?

Not using JWT so may help your issue

**Comment by edwardinchains** [comment]
I was using the code on: [https://github.com/XeroAPI/xero-php-oauth2-app/blob/master/callback.php](url)

I have switched to using the code you linked above and it seems to work ok now
