### ISSUE TITLE
how to set / Edit newly created invoice branding theme 

### ISSUE THREAD

**Issue by redlaw03** [XeroAPI/xero-php-oauth2#310]
Hi
I am able to create an invoice using the xero sdk(https://github.com/XeroAPI/xero-php-oauth2) with php no problem. 
Question: how do I set the newly created invoice 'Terms & Payment Advice (Invoice and Statement)' which usually falls under https://go.xero.com/InvoiceSettings/InvoiceSettings.aspx in the xero console but in php using the api? 
![image](https://user-images.githubusercontent.com/33483616/215583347-462c7563-9ea9-4b95-bc74-ebc686ab1d90.png)

Question 2: how do I set the newly created invoice line item in php using the api?

**Comment by pumpkinball** [comment]
Hi @redlaw03 I'm going to close this one now, if you need further assistance with LineItem arrays, do feel free to contact our friendly API support team on api@support.xero.com.
