### ISSUE TITLE
Can't connect to a UK Xero organisation

### ISSUE THREAD

**Issue by fooman** [XeroAPI/xero-php-oauth2#32]
Still verifying this but judging by the error message that got reported to us it is currently not possible to connect to a UK Xero organisation and retrieve their accounts.

The error message showing is
Invalid value for 'system_account', must be one of 'DEBTORS', 'CREDITORS', 'BANKCURRENCYGAIN', 'GST', 'GSTONIMPORTS', 'HISTORICAL', 'REALISEDCURRENCYGAIN', 'RETAINEDEARNINGS', 'ROUNDING', 'TRACKINGTRANSFERS', 'UNPAIDEXPCLM', 'UNREALISEDCURRENCYGAIN', 'WAGEPAYABLES', ''

which does not list the UK only system accounts as seen here:

CIS Assets (UK Only) | CISASSETS
CIS Labour Expense (UK Only) | CISLABOUREXPENSE
CIS Labour Income (UK Only) | CISLABOURINCOME
CIS Liability (UK Only) | CISLIABILITY
CIS Materials (UK Only) | CISMATERIALS

https://developer.xero.com/documentation/api/types#SystemAccounts

**Comment by fooman** [comment]
My test UK account does not seem to be signed up to CIS https://central.xero.com/s/article/Construction-Industry-Scheme-CIS-in-Xero but judging from the description once enabled it would change the chart of accounts which then conceivably fails the validation.

**Comment by SidneyAllen** [comment]
@fooman - thanks for sharing this feedback - I'll add them to our OpenAPI spec and include these changes in the next release of this SDK.

**Comment by fooman** [comment]
Just to confirm the CIS accounts are the issue. Furthermore the developer documentation is inaccurate for at least some.

The actual values encountered as provided from Xero were

`CISLABOUR` and `CISASSET`

**Comment by SidneyAllen** [comment]
@fooman - checkout version 1.1.2
