### ISSUE TITLE
Custom Fields on API Manual Journal

### ISSUE THREAD

**Issue by ponel-reston** [XeroAPI/xero-php-oauth2#33]
I have custom fiels, branch and division, are they supported on API Manual Journal?

**Comment by SidneyAllen** [comment]
@ponel-reston can you clarify custom fields (branch and division) are you referring to Tracking Categories?

If so, then yes according to our docs they are https://developer.xero.com/documentation/api/journals

**Comment by ponel-reston** [comment]
@SidneyAllen thank you, that's what I was looking for
