### ISSUE TITLE
Feature request: 'create or update' records

### ISSUE THREAD

**Issue by bluec** [XeroAPI/xero-php-oauth2#34]
I think it is common to want to be able to _create or update_ records but currently this client doesn't support it.

A couple of ways I can see this could be done, but I am not sure how you're generating the methods:

1. Generate new `CreateOrUpdateResource()` methods that are the same as the `CreateResource()` methods but use POST instead of PUT when creating the Request object.

1. Add a parameter `$updateIfExists = false` to the `CreateResource()` method signatures then when this is passed as true use POST instead of PUT when creating the Request object.

Any thoughts on having this added? The client feels incomplete without it.

**Comment by SidneyAllen** [comment]
@bluec i have updated our OpenAPI spec and will be including this in our next release

**Comment by bluec** [comment]
Thanks @SidneyAllen do you have any indication when the new release might be? Don't want to hold you to it, but would be useful to have an idea whether it will likely be imminent, or within a week, or month etc.

**Comment by SidneyAllen** [comment]
@bluec - sometime over the next week or two.

**Comment by SidneyAllen** [comment]
@bluec - checkout version 1.1.2

**Comment by bluec** [comment]
Thanks @SidneyAllen  just looking through the changes. Looks like this is nicely implemented.

One thing that strikes me is why the decision to remove the `createSingleResource()` methods? I think I can envisage use cases where it would be useful to only create a resource and get an error if the resource already exists. Also, removing these now means that BankTransaction, Invoice, CreditNote, Contact, Item and PurchaseOrder have different implementations to other resources which seems like an unnecessary inconsistency.

This is a bit of an overlap with #35 but will keep the discussion here. What do you think about implementing the create, update, updateOrCreate methods for both singular and plural resources? This would seem to cover all use cases, e.g.

createResource()
updateResource()
updateOrCreateResource()
createResources()
updateResources()
updateOrCreateResources()

Or do you feel the new implementation already covers these?
