### ISSUE TITLE
SDK is fundamentally broken - syntax errors throughout

### ISSUE THREAD

**Issue by lioneaglesolutions** [XeroAPI/xero-php-oauth2#359]
**SDK you're using (please complete the following information):**
- Version 7.0.0

**Describe the bug**
The SDK has syntax errors through.

https://github.com/XeroAPI/xero-php-oauth2/blob/f46069fe379742394b823866c549b7eda6488901/lib/Models/Accounting/Invoices.php#L290

**To Reproduce**
```php
use XeroAPI\XeroPHP\Models\Accounting\Invoices;

$invoices = new Invoices(); // ERROR  syntax error, unexpected single-quoted string "invoices", expecting "]" in vendor/xeroapi/xero-php-oauth2/lib/Models/Accounting/Invoices.php on line 277.
```

**Expected behavior**
The class to be instantiated.

**Screenshots**
![screenshot-ppQ5pYcX-000963@2x](https://github.com/user-attachments/assets/30f08b1d-f93b-4b91-9570-b99f302544a9)

**Comment by sangeet-joy-tw** [comment]
Hey @lioneaglesolutions 

We have fixed the issue in our new version - v7.0.1. 

Please upgrade and let us know if you face any more issues.
