### ISSUE TITLE
Cannot install on PHP 5.5.29

### ISSUE THREAD

**Issue by pauliak1** [XeroAPI/xero-php-oauth2#36]
When trying to install using composer I get the following error:
Package xeroapi/xero-php-oauth2 at version  has a PHP requirement incompatible with your PHP version (5.5.29)

**Comment by kaythinks** [comment]
Upgrade your php version to at least 7.1

**Comment by SidneyAllen** [comment]
@pauliak1 - I've been developing using version 7.2.1

If possible, I strongly recommend upgrading to a 7.x version.  According to this wikipedia page your version hasn't been supported sing 2016.

https://en.wikipedia.org/wiki/PHP

**Comment by pauliak1** [comment]
thanks. would help others if you update readme requirements to state that as currently has php5.5

**Comment by SidneyAllen** [comment]
@pauliak1 and @kaythinks 

I've done some testing and version 1.6.2 now support PHP 5.6+
