### ISSUE TITLE
Creating Payments

### ISSUE THREAD

**Issue by kaythinks** [XeroAPI/xero-php-oauth2#39]
Hi, i'm trying to create a payment but I keep getting XeroAPI \ XeroPHP \ ApiException (400)
[400] Client error: `PUT https://api.xero.com/api.xro/2.0/Payments` resulted in a `400 Bad Request` response: { "ErrorNumber": 14, "Type": "PostDataInvalidException", "Message": "JSON for post data was invalid,Error conve (truncated...)

Here is my code 
//Create Contact
		$where = 'ContactStatus=="ACTIVE"';
		$getContact = $apiInstance->getContacts($xeroTenantId, null, $where);
		$contactId = $getContact->getContacts()[0]->getContactId();

		$contact = new \XeroAPI\XeroPHP\Models\Accounting\Contact;
		$contact->setContactId($contactId);

		//Create Line Items
        $lineitem = new \XeroAPI\XeroPHP\Models\Accounting\LineItem;
		$lineitem->setDescription('Sample Item')
		->setQuantity(1)
		->setUnitAmount(20)
		->setAccountCode("400");
		$lineitems = [];
		array_push($lineitems, $lineitem);

		$invoice = new \XeroAPI\XeroPHP\Models\Accounting\Invoice;
		$invoice->setReference('Ref-num')
		->setDueDate(new \DateTime('2020-01-02'))
		->setContact($contact)
		->setLineItems($lineitems)
		->setInvoiceID('1234567')
		//->setStatus(\XeroAPI\XeroPHP\Models\Accounting\Invoice::STATUS_AUTHORISED)
		->setType(\XeroAPI\XeroPHP\Models\Accounting\Invoice::TYPE_ACCREC)
		->setLineAmountTypes(\XeroAPI\XeroPHP\Models\Accounting\LineAmountTypes::EXCLUSIVE);

		$payment = new \XeroAPI\XeroPHP\Models\Accounting\Payment;
					$payment->setDate(\DateTime::createFromFormat('Y-m-d', "2020-01-18" ) )
						->setReference('Demo')
						->setInvoice($invoice)
						->setInvoiceNumber('INV-0719')
						->setAmount(10.50);       
Can I get a sample code of how to the createPayment($xero_tenant_id, $payment).
Kindly Assist.

**Comment by SidneyAllen** [comment]
Hi @kaythinks 

From our sample app - we have this code snippet.
https://github.com/XeroAPI/xero-php-oauth2-app

$invoice = new XeroAPI\XeroPHP\Models\Accounting\Invoice;
$invoice->setInvoiceID($invoiceId);

$bankaccount = new XeroAPI\XeroPHP\Models\Accounting\Account;
$bankaccount->setAccountID($accountId);

$payment = new XeroAPI\XeroPHP\Models\Accounting\Payment;
$payment->setInvoice($invoice)
	->setAccount($bankaccount)
	->setAmount("2.00");

$result = $apiInstance->createPayment($xeroTenantId,$payment);

**Comment by kaythinks** [comment]
//Create Payment
		$invoice = new \XeroAPI\XeroPHP\Models\Accounting\Invoice;
		$invoice->setInvoiceID('INV-0719');

		$bankaccount = new \XeroAPI\XeroPHP\Models\Accounting\Account;
		$bankaccount->setAccountID('200');

		$payment = new \XeroAPI\XeroPHP\Models\Accounting\Payment;
		$payment->setInvoice($invoice)
			->setInvoiceNumber('INV-0719')
			->setAccount($bankaccount)
			->setAmount(10.50);
I'm still getting the same error 
XeroAPI \ XeroPHP \ ApiException (400)
[400] Client error: `PUT https://api.xero.com/api.xro/2.0/Payments` resulted in a `400 Bad Request` response: { "ErrorNumber": 14, "Type": "PostDataInvalidException", "Message": "JSON for post data was invalid,Error conve (truncated...)
Kindly assist.

**Comment by SidneyAllen** [comment]
@kaythinks - and for anyone else who come across this issue.

You need to pass in a GUID returned by Xero's API when you create or retrieve existing invoices.  

 The Invoice number and InvoiceID are not the same thing.  Invoice Number is being passed $invoice->setInvoiceID('INV-0719');  will not work.
