### ISSUE TITLE
Not throwing Exception if price is string on creating Items (setPurchaseDetails method) 

### ISSUE THREAD

**Issue by abhinavrazz7272** [XeroAPI/xero-php-oauth2#40]
It seems error and format is not being handled for setPurchaseDetails and setSalesDetails for Item.
It took 5 min and give the following error

XeroAPI\XeroPHP\Models\Accounting\Error Object
(
    [container:protected] => Array
        (
            [error_number] => 
            [type] => 
            [message] => 
            [elements] => 
        )

)
[500] cURL error 18: transfer closed with 42 bytes remaining to read (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by SidneyAllen** [comment]
@abhinavrazz7272  - checkout version 1.1.2

**Comment by abhinavrazz7272** [comment]
Still facing same issue. Please see the request (PurchaseDetails => UnitPrice)

**REQUEST**
`{ 
   "Items":[ 
      { 
         "Code":"ALFPT",
         "Name":"Alfalfa 12 Punnets per tray - Order by TRAY",
         "Description":"Alfalfa 12 Punnets per tray - Order by TRAY",
         "PurchaseDescription":"Alfalfa 12 Punnets per tray - Order by TRAY",
         "PurchaseDetails":{ 
            "UnitPrice":"test",
            "AccountCode":"310",
            "TaxType":"EXEMPTEXPENSES"
         },
         "SalesDetails":{ 
            "UnitPrice":"35.20",
            "AccountCode":"200",
            "TaxType":"EXEMPTOUTPUT"
         }
      }
   ]
}`

**RESPONSE**

`XeroAPI\XeroPHP\Models\Accounting\Error Object
(
[container:protected] => Array
(
[error_number] =>
[type] =>
[message] =>
[elements] =>
)

)
[500] cURL error 18: transfer closed with 42 bytes remaining to read (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)`
