### ISSUE TITLE
Various methods have incorrect type hints

### ISSUE THREAD

**Issue by filliph** [XeroAPI/xero-php-oauth2#41]
The `setLineAmountTypes` method (as well as a bunch of other methods in other models, such as `setCurrencyCode`) are type hinted to want `\XeroAPI\XeroPHP\Models\Accounting\LineAmountTypes` (or similar), but these classes are not models, they are a storage classes for constants.

The example app at https://github.com/XeroAPI/xero-php-oauth2-app uses this line:
`->setLineAmountTypes(\XeroAPI\XeroPHP\Models\Accounting\LineAmountTypes::EXCLUSIVE)` which does not meet the type hinting requirements of the method:

<img width="786" alt="image" src="https://user-images.githubusercontent.com/9424286/73020715-22ae2300-3e1e-11ea-9d84-638e5b2e07f1.png">

There doesn't appear to be any errors while passing a normal string, but it might be worth fixing this regardless in order to be less confusing for other developers :)

**Comment by SidneyAllen** [comment]
@filliph - thanks for the feedback.

Our SDKs are generated from our OpenAPI Specs.  So attributes like LineAmountTypes are of type=string and have a related ENUM.

https://github.com/XeroAPI/Xero-OpenAPI/blob/master/accounting-yaml/Xero_accounting_2.0.0_swagger.yaml#L18584

If you have an example of what change would need to happen and where in the library, I can see how hard that would be to implement in the mustache templates our PHP sdk is based off.

**Comment by filliph** [comment]
I'm not familiar with how OpenAPI works so unfortunately I can't provide any PRs, but it does produce invalid type hints for these functions:

```
    /**
     * Sets currency_code
     *
     * @param \XeroAPI\XeroPHP\Models\Accounting\CurrencyCode|null $currency_code currency_code
     *
     * @return $this
     */
    public function setCurrencyCode($currency_code)
    {
        $this->container['currency_code'] = $currency_code;

        return $this;
    }
```

```
    /**
     * Sets line_amount_types
     *
     * @param \XeroAPI\XeroPHP\Models\Accounting\LineAmountTypes|null $line_amount_types line_amount_types
     *
     * @return $this
     */
    public function setLineAmountTypes($line_amount_types)
    {
        $this->container['line_amount_types'] = $line_amount_types;

        return $this;
    }
```

**Comment by filliph** [comment]
I think the problem might be this line: https://github.com/XeroAPI/Xero-OpenAPI/blob/master/accounting-yaml/Xero_accounting_2.0.0_swagger.yaml#L18514

Compare that with the Type, which works fine: https://github.com/XeroAPI/Xero-OpenAPI/blob/master/accounting-yaml/Xero_accounting_2.0.0_swagger.yaml#L18481

My guess is, when you use the `$ref:` it will type hint it as expecting an object of that type.

**Comment by hailwood** [comment]
@SidneyAllen 

Pretty sure @filliph is 90% correct here, it should be the combination of using $ref without also specifying a type.

Could you try adding a type as well as the $ref and see what happens e.g. 

https://github.com/XeroAPI/Xero-OpenAPI/blob/master/accounting-yaml/Xero_accounting_2.0.0_swagger.yaml#L19714 is

```yaml
CurrencyCode:
  $ref: '#/components/schemas/CurrencyCode'
```

What is generated on the docblock of `Invoice#setCurrencyCode` if you do

```yaml
CurrencyCode:
  $ref: '#/components/schemas/CurrencyCode'
  type: string
```

Pretty sure that should fix these.

If we can confirm that will fix it then I'm happy to go through and add the types where the enums are referenced.

**Comment by SidneyAllen** [comment]
@filliph and @hailwood 

I've added the type:string datatype to the OAS for enums.  This required modifying the mustache templates we use to generate the code, but it looked good so I've release version 1.1.3.  

When you have a moment, if you could look at the Organisation model and the CountryCode to see if the hint shows the correct "string" datatype?

**Comment by filliph** [comment]
@SidneyAllen no, it does not, nor does any other model.

```
    /**
     * Sets country_code
     *
     * @param \XeroAPI\XeroPHP\Models\Accounting\CountryCode|null $country_code country_code
     *
     * @return $this
     */
    public function setCountryCode($country_code)
    {
        $this->container['country_code'] = $country_code;

        return $this;
    }
```

**Comment by SidneyAllen** [comment]
@filliph 
Looks like the mustache template has two locations.... I only changed the comments above the "getters"

/**
     * Gets country_code
     *
     * @return string|null
     */
    public function getCountryCode()
    {
        return $this->container['country_code'];
    }

Can you confirm the above change is correct and would work for setters as well?

**Comment by filliph** [comment]
Ah, you're quite right, it does work for the getters from what I can tell!

**Comment by SidneyAllen** [comment]
@filliph - ok version 1.1.4 publishing to packagist.

**Comment by filliph** [comment]
Confirmed, thank you!

**Comment by slifin** [comment]
I think `XeroAPI\XeroPHP\Models\Accounting\Invoice->setCurrencyCode()` also exhibits this behaviour the type hint asks for the class `XeroAPI\XeroPHP\Models\Accounting\CurrencyCode`  but there's no way to load that object with a currency code but it does contain a list of valid constants that are strings

**Comment by SidneyAllen** [comment]
@slifin - I recommend looking at version 1.1.4.

Looking at the Invoice model > setCurrencyCode I see the following

 /**
     * Sets currency_code
     *
     * @param string|null $currency_code currency_code
     *
     * @return $this
     */
    public function setCurrencyCode($currency_code)
    {
        $this->container['currency_code'] = $currency_code;

        return $this;
    }
