### ISSUE TITLE
Requst method for migrating OAuth1.0a tokens to OAuth2.0 tokens.

### ISSUE THREAD

**Issue by abhinavrazz7272** [XeroAPI/xero-php-oauth2#45]
I would like to request you to implement the feature to migrate existing connecton of partner app to OAuth2.0

Thank you

**Comment by admo26** [comment]
Hi, the migration endpoint requires OAuth1.0a for authorization so we won't be adding it to the OAuth 2.0 SDKs. 

We've released a C# sample [here](https://github.com/XeroAPI/xero-net-oauth2-sampletokenmigration). It's not PHP, but the flow should be clear enough that it can be applied to your current implementation.
