### ISSUE TITLE
createContact method missing

### ISSUE THREAD

**Issue by hailwood** [XeroAPI/xero-php-oauth2#47]
It looks like the API might be missing the `createContact` method?
There is only `createContacts`

**Comment by SidneyAllen** [comment]
Hi @hailwood 

Without getting to into the weeds - we are now generating all our SDKs off our OpenAPI Specs.  The thought we could leverage the "PUT" and "POST" on the root endpoint to support methods for both singular and multiple/bulk create for endpoints that support that functionality.  

I missed the fact that endpoints that support Multiple/Bulk create ALSO support multiple/bulk update.  For this reason, we need to replace the "createContact" with "updateOrCreateCotact" method.

The createContacts method is requires an Array of contacts to be passed and therefore can be used for single OR multiple create.  Just push one object on the array to perform a single create.

we've removed the "createContact" method

**Comment by hailwood** [comment]
Thanks @SidneyAllen probably worth removing it from the docs as well next time you run the generator?

https://github.com/XeroAPI/xero-php-oauth2/blob/master/docs/Api/AccountingApi.md#createcontact
