### ISSUE TITLE
How do I create contacts?

### ISSUE THREAD

**Issue by hailwood** [XeroAPI/xero-php-oauth2#48]
So the API docs for creating a contact are completely wrong, they drop into a javascript state at one point...

Figured I'd try and do it based off the docblocks which suggest

```php
$contact = new Contact();
$contact->setFirstName($user->first_name);
//...

$contacts = $apiInstance->createContacts($tenantId, new Contacts([$contact]));
```

But that gives us the error that we didn't pass any data along, Specifically

```json
{
  "ErrorNumber": 17,
  "Type": "NoDataProcessedException",
  "Message": "No data has been processed for this endpoint. This endpoint is expecting Contact data to be specifed in the request body."
}
```

So looking at the actual api docs on the website, and combing through the code it looks like we actually need to do 

```php
$contacts = $apiInstance->createContacts($tenantId, ['Contacts' => [$contact]]);
```
Which works, but it's what's suggested by the docs in this package or the API docs!
I can get my application working using this method, but since the docs say to do it another way, I'm not convinced that the next update of this package isn't going to break the way I'm doing it?

**Comment by SidneyAllen** [comment]
Below is an example of how to create a contact ....

$arr_contacts = [];	

$contact_1 = new XeroAPI\XeroPHP\Models\Accounting\Contact;
$contact_1->setName('FooBar123')
	->setFirstName("Foo")
	->setLastName("Bar")
	->setEmailAddress("ben.bowden@24locks.com");
array_push($arr_contacts, $contact_1);
	
$contacts = new XeroAPI\XeroPHP\Models\Accountig\Contacts;
$contacts->setContacts($arr_contacts);

$result = $apiInstance->createContacts($xeroTenantId,$contacts);

**Comment by hailwood** [comment]
Ah right I see now,
I also see that rather than using 

```php
$contacts = new XeroAPI\XeroPHP\Models\Accounting\Contacts;
$contacts->setContacts($arr_contacts);
```

You can do 
```
$contacts = new XeroAPI\XeroPHP\Models\Accounting\Contacts(['contacts' => $arr_contacts])
```
The missing step was passing the contacts as a sub array to the contacts key.

Little odd given the only thing you can pass into the constructor is a list of contacts, but we'll roll with it.

**Comment by andyunleashed** [comment]
@hailwood - is this use of the contacts key likely to change so it's not required? I want to update our integration to the new version but don't want to do a wide update if it's likely to get dropped.

**Comment by hailwood** [comment]
@andyunleashed make sure you take a peak at #51 especially point 4 as it relates to this.
