### ISSUE TITLE
parse error in  AccountingObjectSerializer

### ISSUE THREAD

**Issue by kyegil** [XeroAPI/xero-php-oauth2#49]
There is a double function statement in /lib/AccountingObjectSerializer.php line 50 on version 1.1.0 and 1.1.1.
The issue is fixed in version 1.1.2, but this version also has an added php >=7.2.1 requirement.
When installing via composer the latest available version e.g. when on php 7.1 or lower is 1.1.1 which throws a php parse error.

**Comment by SidneyAllen** [comment]
@kyegil - I got reports the SDK didn't work with version 5.5.  I'm running 7.2.1 so can only confidently vouch that it works for that version and higher.  Looking at PHP versions and deprecation schedule 7.2.1 seemed reasonable.

I'm happy to push a release that loosens up the version requirement, but would like to hear from the our PHP devs around what version is appropriate and can be validated.

https://en.wikipedia.org/wiki/PHP

**Comment by kyegil** [comment]
Hi. To clarify: My main issue is not that version 1.1.2 is not available to me, but that the latest available version for php7.1 is a broken version (1.1.1).
In my case composer automatically installed 1.1.1 (which only requires php5.6), and I had to constrain this and downgrade to "1.0.10"

**Comment by SidneyAllen** [comment]
@kyegil  - yes 1.1.1 is broken.  I was working on the object deserializer code and released 1.1.2 to fix it.  

I'm happy to push a release where version requirement in composer is 7.1, would you be willing to validate the SDK for that version after I publish it?

**Comment by SidneyAllen** [comment]
Closing this one as similar discussion happening on #46
