### ISSUE TITLE
Dotenv isn't a dependency - should it be

### ISSUE THREAD

**Issue by sarahk** [XeroAPI/xero-php-oauth2#52]
I've had to install it separately which is causing problems, looks like it should be in the package.

**Comment by hailwood** [comment]
I assume you're asking this question from [looking at the demo app](https://github.com/XeroAPI/xero-php-oauth2-app/blob/master/authorization.php#L6-L10).

To answer your question, no this library should not have Dotenv as a dependency as it depends on what framework you're using as to how you'd actually store/read the credentials.

Most frameworks include .env file reading either as a dependency, or ship with their own version.
E.g. 
* Symfony uses symfony/dotenv
* Laravel uses vlucas/phpdotenv
* Codeigniter4 uses it's own internal thing

Other frameworks don't have any .env reading and leave it up to you to store them somewhere (yii, cakephp etc) e.g. you might look at setting the keys as real environment variables on your server.

 It just happens to be the chosen method for the example app as it's not using any framework (and you'll note [the example app itself **does** require it as a dependency](https://github.com/XeroAPI/xero-php-oauth2-app/blob/master/composer.json#L8)).

**Comment by sarahk** [comment]
OK, cool, if that's the only place it's used then out it goes!

**Comment by SidneyAllen** [comment]
@sarahk - yep  dotenv was added to the sample app to make it easier to config your API keys in one location and have them available to different bits of code in the sample app.

So, short answer - no dotenv is not required to use xero-php-oauth2 SDK.
