### ISSUE TITLE
Can we have the generator make traits?

### ISSUE THREAD

**Issue by hailwood** [XeroAPI/xero-php-oauth2#53]
Right now the generator creates a class that is over 63,000 lines long.
It's so big github can't even display it which means linking to specific lines for issues etc doesn't work, and well navigating it really isn't much fun.

It would be great if the generator could instead split everything by entity so we'd end up with something like (bodies/docblocks removed for brevity)

```php
<?php

namespace XeroAPI\XeroPHP\Api\Concerns;

trait Accounts
{

    public function createAccount($xero_tenant_id, $account)
    {
    }

    public function createAccountWithHttpInfo($xero_tenant_id, $account)
    {
    }

    public function createAccountAsync($xero_tenant_id, $account)
    {
    }

    public function createAccountAsyncWithHttpInfo($xero_tenant_id, $account)
    {
    }

    protected function createAccountRequest($xero_tenant_id, $account)
    {
    }

}
```

```php
<?php

namespace XeroAPI\XeroPHP\Api;

class AccountingApi
{

    use Concerns\Accounts;

    protected $client;

    protected $config;

    protected $headerSelector;

    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
    }

    public function getConfig()
    {
    }

}
```

Then as a developer I could quickly open up the Accounts trait to see all the method that are available to me for Accounts, rather than trying to scan a 63,000 line file!

**Comment by SidneyAllen** [comment]
@hailwood - I've moved this question over to https://github.com/XeroAPI/Xero-OpenAPI/issues/134 as the request goes beyond the php sdk.
