### ISSUE TITLE
getDate() & getDueDate() return string instead of DateTime

### ISSUE THREAD

**Issue by ndkhaivn** [XeroAPI/xero-php-oauth2#54]
getDate() and getDueDate() from Invoice are returning string, instead of DateTime as specified in docs

**Comment by SidneyAllen** [comment]
@ndkhaivn which version of the SDK are you using?

**Comment by ndkhaivn** [comment]
I was using v1.0.1 before, the issue is fixed when I update to the lastest release. Thank you.
