### ISSUE TITLE
Installation instructions incorrect

### ISSUE THREAD

**Issue by robertclarkson** [XeroAPI/xero-php-oauth2#6]
Hi! thanks for providing this handy library.
Your installation instructions are;
```
To install the bindings via Composer, add the following to composer.json:

"require": {
    "xeroapi/xero-php-oauth2": "0.2.7"
}
Then run composer install
```
composer install installs from the composer.lock file which does not read from the composer.json.

I would have thought the correct installation instructions are to call 
```
composer require xeroapi/xero-php-oauth2
```

**Comment by SidneyAllen** [comment]
@robertclarkson  thanks for the feedback.

While both ways technically work - yours it a bit better (avoid the composer.lock) confusion.  If you are starting from scratch you could add the bindings directly and run composer install.

Readme Updated

**Comment by calcinai** [comment]
@robertclarkson @SidneyAllen  +1

`composer require` also does a better job of picking the correct version of the library if you've got conflicting dependencies or platform requirements.  Overall a better idea.
