### ISSUE TITLE
Invoice Prepayments/Overpayments/Credit Notes don't report the `AppliedAmount`

### ISSUE THREAD

**Issue by IanSimpson** [XeroAPI/xero-php-oauth2#65]
**SDK you're using (please complete the following information):**
 - Version 1.2.0

**Describe the bug**
Using the `getInvoice` (or presumably `getInvoices`) function to get an invoice returns an Invoice object with children Prepayments, Overpayments and CreditNotes. These are (logically) collections of Prepayment, Overpayment and CreditNote objects respectively.

However the data returned by the Invoices endpoint doesn't include many of the fields for these three objects, and notably DOES include an "AppliedAmount" field, which is NOT available through the objects.

This means there's no way to see what proportion of the Credit has been applied to the invoice you're looking at.

**To Reproduce**
1. Set up a test invoice with a Credit Note, Prepayment or Overpayment applied (or all three!)
2. Run `print_r($apiclient->getInvoices($tenant_id, [The invoice GUID]));`
3. Be frustrated that you can't see the amount that was applied.

**Expected behavior**
I should be able to do something like `$res->getInvoices()[0]->getOverpayments()[0]->getAppliedAmount()` to see the applied amount.

**Screenshots**
The raw JSON from the request, showing the AppliedAmount:
![image](https://user-images.githubusercontent.com/782493/74594565-98607580-4ffd-11ea-932d-f2afba9e92bc.png)

The deserialized output, where the AppliedAmount is now a total mystery:
![image](https://user-images.githubusercontent.com/782493/74594552-81218800-4ffd-11ea-82e0-6798070a9d9c.png)

**Comment by SidneyAllen** [comment]
@IanSimpson - thanks for the feedback.  We've update our OpenAPI specs and released 1.3.0 of xero-php-oauth2

The follow returns the applied amount from the child object.
$result2->getInvoices()[0]->getCreditNotes()[0]->getAppliedAmount());

This was added for CreditNotes, Prepayments and Overpayments
