### ISSUE TITLE
Create Items `400 Bad Request`

### ISSUE THREAD

**Issue by deep12650** [XeroAPI/xero-php-oauth2#66]
**SDK you're using (please complete the following information):**
 - Version [e.g. 1.2]

**Describe the bug**
Couldn't able to figure out why this error is coming. I am sending all data as per defined in the docs.

**Request**
`{"Items":[{"Code":"SKU-197","Name":"Moisture Mist Balancing Gel Mist","Description":"Moisture Mist Balancing Gel Mist Moisture Mist Balancing Gel Mist It can be used under makeup as a pre-makeup base or over makeup for added moisture during the day.\n","InventoryAssetAccountCode":630,"PurchaseDetails":{"UnitPrice":17.39130714285714,"TaxType":"INPUT2","COGSAccountCode":"310"},"SalesDetails":{"UnitPrice":24.34783,"TaxType":"OUTPUT2","AccountCode":"200"},"IsSold":true,"IsPurchased":true,"IsTrackedAsInventory":true}]}`

**Error**
`XeroAPI\XeroPHP\ApiException thrown with message "[400] Client error: `PUT https://api.xero.com/api.xro/2.0/Items?summarizeErrors=true&unitdp=4` resulted in a `400 Bad Request` response: {   "ErrorNumber": 17,   "Type": "NoDataProcessedException",   "Message": "No data has been processed for this endpoi (truncated...) "`

**Comment by SidneyAllen** [comment]
@deep12650 

I've tested your payload (with a few modifications to substitute valid tax types and account codes for my Xero org).  This is the raw JSON

{"Items":[{"Code":"SKU-198","InventoryAssetAccountCode":140,"Name":"Moisture Mist Balancing Gel Mist","Description":"Moisture Mist Balancing Gel Mist Moisture Mist Balancing Gel Mist It can be used under makeup as a pre-makeup base or over makeup for added moisture during the day.\n","PurchaseDetails":{"UnitPrice":17.39130714285714,"COGSAccountCode":310,"TaxType":"INPUT"},"SalesDetails":{"UnitPrice":24.34783,"COGSAccountCode":400,"TaxType":"OUTPUT"},"IsTrackedAsInventory":true}]}

But you can't just pass raw JSON (if that's what you were doing. You'll need to create objects and set the value of properties.  below is the PHP code I used to validate your values.

`
$arr_items = [];	

$purchase = new XeroAPI\XeroPHP\Models\Accounting\Purchase;
$purchase->setUnitPrice(17.39130714285714)
	->setTaxType(INPUT)
	->setCOGSAccountCode(310);

$sales = new XeroAPI\XeroPHP\Models\Accounting\Purchase;
$sales->setUnitPrice(24.34783)
	->setTaxType(OUTPUT)
	->setCOGSAccountCode(400);

$item_1 = new XeroAPI\XeroPHP\Models\Accounting\Item;
$item_1->setName("Moisture Mist Balancing Gel Mist")
	->setCode("SKU-198")
	->setDescription("Moisture Mist Balancing Gel Mist Moisture Mist Balancing Gel Mist It can be used under makeup as a pre-makeup base or over makeup for added moisture during the day.\n")
	->setIsTrackedAsInventory(true)
	->setInventoryAssetAccountCode(140)
	->setSalesDetails($sales)
	->setPurchaseDetails($purchase);
array_push($arr_items, $item_1);

$items = new XeroAPI\XeroPHP\Models\Accounting\Items;
$items->setItems($arr_items);

$result = $apiInstance->createItems($xeroTenantId,$items,true,4); `
