### ISSUE TITLE
When it changes from php >= 5.6 to >= 7.2

### ISSUE THREAD

**Issue by mmoradeveloper** [XeroAPI/xero-php-oauth2#69]
I had an issue that has been resolved in future pushes but now the project won't allow me to update to the latest project.

what changes between  version ^1.1 and ^1.2 to make that decision?
what can I do to make it work not with php 7?

version 1.1.1 php >= 5.6

Error:
FatalErrorException: Parse: syntax error, unexpected 'function' (T_FUNCTION), expecting identifier (T_STRING) in .../vendor/xeroapi/xero-php-oauth2/lib/IdentityObjectSerializer.php line 50

Thanks

**Comment by mmoradeveloper** [comment]
version 1.1.1 php >= 5.6 

Error: 
FatalErrorException: Parse: syntax error, unexpected 'function' (T_FUNCTION), expecting identifier (T_STRING) in /var/www/html/experttrades/vendor/xeroapi/xero-php-oauth2/lib/IdentityObjectSerializer.php line 50

**Comment by SidneyAllen** [comment]
@mmoradeveloper 

We've set PHP 7.2.1 as that's the version we are testing against.
https://github.com/XeroAPI/xero-php-oauth2/issues/49

You could try to install and ignore the PHP requirement per this stackoverflow answer.
"run composer with the --ignore-platform-reqs argument"

https://magento.stackexchange.com/questions/207318/php-requirement-incompatible-with-your-php-version-composer-module-installatio

We are open to loosening the PHP version requirement, but would like to hear from the community that they've tested the SDK on version 5.x and shared the outcome with us.

**Comment by wobinb** [comment]
The latest update, should have resolved this here: https://github.com/XeroAPI/xero-php-oauth2/pull/110

Please let us know if not.

**Comment by SidneyAllen** [comment]
@mmoradeveloper - I've done some testing with PHP 5.6.  Please try xero-php-oauth2 version 1.6.2 which has been tested and now requires PHP 5.6+
