### ISSUE TITLE
Get Tax Rates Error on deserializer

### ISSUE THREAD

**Issue by mmoradeveloper** [XeroAPI/xero-php-oauth2#7]
Hi,
I found that when I am trying to get the Tax Rates because they are some of the results the 
status = "PENDING" I get an error and I can not have the taxes back.

is due that TaxRate.php have only set statuses as 'ACTIVE', 'DELETED', 'ARCHIVED'

**Comment by SidneyAllen** [comment]
Added in release 1.0.0
