### ISSUE TITLE
How to create Invoice

### ISSUE THREAD

**Issue by nitinmahajaneluminous** [XeroAPI/xero-php-oauth2#72]
Hi

I am trying to create an invoice using XERO Oauth 2.0 PHP SDK . But I am getting the following error.

"[400] Client error: `PUT //api.xero.com/api.xro/2.0/Invoices` resulted in a `400 Bad Request` response:{ "ErrorNumber": 14, "Type": "PostDataInvalidException", "Message": "JSON for post data was invalid,Error conve (truncated...)" .

I am also posting my code patch here which is i have used to create invoice .

$apiInstance = new AccountingApi($client,$config);

$Contact = $apiInstance->getContact($xeroTenantId, "8959220a-1c66-417c-b39c-50d8975df93c");

$invoice = new Invoice();

$dateInstance = new \DateTime(date('Y-m-d'));

           $lineitem = new LineItem;

           $lineitem = $lineitem->setDescription('Deposit for VBA Course')

                       ->setQuantity(1.0)

                       ->setUnitAmount(200.0)

                       ->setAccountCode(200)

                       ->setTaxType(0.00)

                       ->setTaxAmount(0.00)

                       ->setLineAmount(200.0);       

           $invoice = $invoice->setType('ACCREC')

                   ->setContact($Contact)

                   ->setLineItems($lineitem)

                   ->setDate($dateInstance)

                   ->setDueDate($dateInstance)

                   ->setInvoiceNumber('PCP001')

                   ->setReference("8959220a-1c66-417c-b39c-50d8975df93c")

                   ->setStatus("AUTHORISED")

                   ->setLineAmountTypes('Exclusive');

$summarize_errors = True;

$result = $apiInstance->createInvoice($xeroTenantId, $invoice, $summarize_errors);

I am not getting whats wrong with that code.

I have created the contact with same SDK, and it was created successfully.

But not able to create invoice.

Could you please look at this one?

Thank you

**Comment by wobinb** [comment]
Hi

It looks like the the line item is being passed as a single object. The SDK is expecting this to be an array.

You could add the following code:

`$arr_lineitems = [];
array_push($arr_lineitems, $lineitem);`

and then pass $arr_lineitems into the Invoice with:

`->setLineItems($arr_lineitem)`
