### ISSUE TITLE
Error accessing: Organisation data

### ISSUE THREAD

**Issue by ronjo** [XeroAPI/xero-php-oauth2#73]
I tried the example described in the YT video Getting started with Xero PHP OAuth 2.0 SDK from scratch

On the second step when my script wants access to:
Organisation data

I get the follwing error:
Parse error: syntax error, unexpected 'function' (T_FUNCTION), expecting identifier (T_STRING) in /home/mydomain/public_html/xero/vendor/xeroapi/xero-php-oauth2/lib/IdentityObjectSerializer.php on line 50

**Comment by SidneyAllen** [comment]
@ronjo - what version of the SDK are you using?

**Comment by ronjo** [comment]
I guess the latest. In the README it say: 
# Xero PHP oAuth2
## Current release of SDK with oAuth 2 support

**Comment by ronjo** [comment]
And in composer it say:
 "xeroapi/xero-php-oauth2": "^1.1"

**Comment by ronjo** [comment]
on line 50 in IdentityObjectSerializer.php
it say:
    public static function function isDate($value) 

should it really be to function after each other?

**Comment by SidneyAllen** [comment]
Try updating to the latest version 1.2.2
