### ISSUE TITLE
Recommended Laravel Integration

### ISSUE THREAD

**Issue by hailwood** [XeroAPI/xero-php-oauth2#74]
Hey @SidneyAllen,

This one's not a bug :) Instead I'd like to offer up our package to be added in the docs as a recommended integration between this package and Laravel. Our company uses Xero in a *lot* of projects, so this package will always be in working order.

https://github.com/webfox/laravel-xero-oauth2
https://packagist.org/packages/webfox/laravel-xero-oauth2

Regards,
Matt

**Comment by SidneyAllen** [comment]
@hailwood - Done!  thank you
