### ISSUE TITLE
Create Payment '400 Bad Request'

### ISSUE THREAD

**Issue by txhaferasi** [XeroAPI/xero-php-oauth2#75]
Receving bad request without a reason. Below is what i am sending. Is this right?!

$payment = new XeroAPI\XeroPHP\Models\Accounting\Payment();
            $payment->setDate($date)
                ->setAmount($amount)
                ->setCode($account_code)
                ->setInvoiceNumber($invoice_id);
$apiResponse = $apiInstance->createPayment($xeroTenantId, $payment);

**Comment by SidneyAllen** [comment]
@txhaferasi - try the following code

$invoice = new XeroAPI\XeroPHP\Models\Accounting\Invoice;
$invoice->setInvoiceID($invoiceId);

$bankaccount = new XeroAPI\XeroPHP\Models\Accounting\Account;
$bankaccount->setAccountID($accountId);

$payment = new XeroAPI\XeroPHP\Models\Accounting\Payment;
$payment->setInvoice($invoice)
	->setAccount($bankaccount)
	->setAmount("2.00");

$result = $apiInstance->createPayment($xeroTenantId,$payment);
