### ISSUE TITLE
IdentityConfiguration does not exist

### ISSUE THREAD

**Issue by thomasedwards** [XeroAPI/xero-php-oauth2#82]
- Version 1.4.0

The documentation references `XeroAPI\XeroPHP\IdentityConfiguration`, no such class exists.

**To Reproduce**
1. Follow instructions in the readme for `callback.php`
2. Run the script
3. `Class 'XeroAPI\XeroPHP\IdentityConfiguration' not found`

**Expected behavior**
The file should exist, or the docs should be updated.

**Comment by SidneyAllen** [comment]
@thomasedwards 

Thank you for catching that - README corrected!

**Comment by thomasedwards** [comment]
Super! Thanks!
