### ISSUE TITLE
Webhook, ITR - "Response not 200"

### ISSUE THREAD

**Issue by manojn-arkenea** [XeroAPI/xero-php-oauth2#84]
**SDK you're using (please complete the following information):**
 - Version [1.2]

**Describe the bug**
When I tried to connect webhook using send "Intent to receive", I am receiving response "Response not 200". I used laravel 5.1 framwork in my project. But when I tried to connect using php code means without laravel framework then I am able to connect and getting "OK" Response in Status. I attached screenshot for the same.

Below is the code I used in for webhooks ITR verification.

$rawPayload = file_get_contents("php://input");
$webhookKey = "5L9DhiXLXPg6MB0uxtz7deJB9NXUsj4CC5QuXfaqNuij8FDnZ2hdAJ7lea3aNEdnA5aJfJLMDDTpDBe+2g4JXQ==";
$computedSignatureKey = base64_encode(hash_hmac('sha256', $rawPayload, $webhookKey, true));
$xeroSignatureKey = $_SERVER['HTTP_X_XERO_SIGNATURE'];
if (hash_equals($computedSignatureKey, $xeroSignatureKey)) {
    http_response_code(200);
} else {
    http_response_code(401);
}

**To Reproduce**
1. Go to 'Webhooks'
2. Click on send "Intent to receive"

**Expected behavior**
Status should be "OK"

Please let me know where I went wrong while connecting using Laravel.

Thanks in advance,
Manoj

![Xero-ITR](https://user-images.githubusercontent.com/35332303/76677812-9091f200-65f8-11ea-8be3-218e2c14f047.png)

**Comment by SidneyAllen** [comment]
@manojn-arkenea  - your question is not directly related to the php SDK.

I did write a blog post on using webhooks and PHP which might be helpful.
https://devblog.xero.com/lets-play-web-hooky-with-php-34a141dcac0a

If you continue to have questions, please drop an email to api@xero.com.
