### ISSUE TITLE
Get GST Overdue

### ISSUE THREAD

**Issue by jasminder** [XeroAPI/xero-php-oauth2#86]
I have tried the reports and other end points but couldn't find the GST Due stats in php sdk .

**Comment by SidneyAllen** [comment]
@wobinb or @dev-welli  - nudge

**Comment by jasminder** [comment]
This is sad to know there is no direct way available to get GST Report via API . I had ticket chat with one of xero support person. All i get is the alternate ways to reach GST but still not accurate.

**Comment by dev-welli** [comment]
Hi there,

Unfortunately as my colleague mentioned, this is not something that exposed via API.

Apologies for the inconvenience caused.

**Comment by SidneyAllen** [comment]
@jasminder - we appreciate your feedback, but this request can't be solved at the SDK level.  The best place to voice your request for new API functionality is in our UserVoice.

https://xero.uservoice.com/forums/5528-xero-accounting-api

This is where developers can up vote requests they want to see built.
