### ISSUE TITLE
Storing Auth Token with Refresh Token and using them without storage.php

### ISSUE THREAD

**Issue by jasminder** [XeroAPI/xero-php-oauth2#89]
I am storing auth token and refresh token and for the future request(happens once in a week), i use the following method to get new auth token: 
```
$provider = new \League\OAuth2\Client\Provider\GenericProvider([
    'clientId'                => '26F7129FF052432696BC9447BAA91A67',
    'clientSecret'            => 'XO84P5D6nVupyaZVJ1DTHumDL6WJNuli09owRd-f852at_W5',
    'redirectUri'             => 'https://bbclients.com.au/api/user/xero/callback.php',
    'urlAuthorize'            => 'https://login.xero.com/identity/connect/authorize',
    'urlAccessToken'          => 'https://identity.xero.com/connect/token',
    'urlResourceOwnerDetails' => 'https://api.xero.com/api.xro/2.0/Organisation'
  ]);
 
  $newAccessToken = $provider->getAccessToken('refresh_token', ['grant_type'=>'refresh_token','refresh_token' => 'refresh_token_from_db']);
```
Using this code to create instance : 
```
$config = XeroAPI\XeroPHP\Configuration::getDefaultConfiguration()->setAccessToken( $newAccessToken );
 $apiInstance = new XeroAPI\XeroPHP\Api\AccountingApi(new GuzzleHttp\Client(),$config);
```
But for future requests its throwing . : 
`Uncaught League\OAuth2\Client\Provider\Exception\IdentityProviderException: invalid_grant`

I am using storing the latest refresh token by comparing with the stored one. Not sure why i am getting this error.

**Comment by rodjsta** [comment]
@jasminder see issue #29 and my comment from 30 Jan

**Comment by jasminder** [comment]
@rodjsta 
I checked it. My issue is, do i really have to use the storage class when i have the refresh token and access token.

**Comment by rodjsta** [comment]
@jasminder, sorry more specifically my comment around disconnecting your app from within the Connected Apps section of Xero and going through the connection process again.

**Comment by jasminder** [comment]
Thanks . i will try and get back to you.

**Comment by wobinb** [comment]
@jasminder ,  the version of storage.php in the readme will store the tokens as session variables. The idea being that you would modify if to store them someplace more secure and permanent - typically a database.

**Comment by jasminder** [comment]
@wobinb Yes, i stored refresh token and access token in db. For any future api calls i request a new access token by passing the refresh token as in example above. Not sure why the grant error popped up.

**Comment by SidneyAllen** [comment]
@jasminder - I've looked at your code and it resembles the sample code I've been using in our sample app.  I've never encountered any issues refreshing the token.

I recommend you do some additional debugging around the first access token you receive and new token you receive when performing the refresh token.

Does the refresh token you receive back on the first access token call match what you retrieve from the DB?  Just throwing out things to check.

You have 3 actions happening above.  ...

- getAccessToken(with all the refreshtoken bits)
- config
- apiInstance

You should narrow down which line of code is throwing the error and investigate further.
