### ISSUE TITLE
oauth2 Private or Authorization Bypass

### ISSUE THREAD

**Issue by Cloudinnovates** [XeroAPI/xero-php-oauth2#9]
Hi, 

I am using oauth2 to post data from my client's system to their XERO account.
How can I bypass the authorization without my client's authorizing it? Since there is only one account to manage.

**Comment by MattR-Api** [comment]
Hi @Cloudinnovates

Thanks for getting in touch.

As this isn't a PHP Example App or SDK issue, I'm going to shut this thread down.

However to answer your question, you're unable to bypass the Authorisation, apps must be initially Authorised by a user. If you've included the offline_access scope, you can use then use the refresh token to swap out your access tokens once Authorised. For more information, please see OAuth 2.0 Documentation on the Developer Center.

For future reference, if you have a general Support Question, like the one you've asked above, please either email us at api@support.xero.com or raise a case with us on our Xero Central site.

Kind Regards

Matt
