### ISSUE TITLE
When create a payment validation error occurred

### ISSUE THREAD

**Issue by chirag2324** [XeroAPI/xero-php-oauth2#90]
**SDK you're using (please complete the following information):**
 - Version [e.g. 1.4]

**Describe the bug**
When I make a request for creating payment using below it gives validation errors.

`
$config = Configuration::getDefaultConfiguration()->setAccessToken( (string)$user->access_token );
          $apiInstance = new \XeroAPI\XeroPHP\Api\AccountingApi(
                new Client(),
                $config
            );

try {

                    $payment = new Payment();

                    $invoice = $apiInstance->getInvoice($xeroTenantId,'ac444de3-d2e8-4280-bdf2-4419b2b7efd9');
                    $payment->setInvoice($invoice);
                    $payment->setAmount(8900);
                    $account = $apiInstance->getAccount($xeroTenantId,'4be62031-e5b8-44a6-aedd-8d2da143bd10');
                    $payment->setAccount($account);
                    //$payment->setBankAccountNumber('35BC7AB148D94A089A9DE182B9612436');
                    //$payment->setCode('970');

                    $apiResponse = $apiInstance->createPayment($xeroTenantId,$payment);
                    $message = $apiResponse;

                } catch (\XeroAPI\XeroPHP\ApiException $e) {
                    $error = AccountingObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\XeroAPI\XeroPHP\Models\Accounting\Error',
                        []
                    );
                    $message = "ApiException - " . $error;
                }`

**Screenshots**
![127 0 0 1 8000 xero_exchange action 6](https://user-images.githubusercontent.com/55869433/77912319-f6949f80-72af-11ea-9082-99a4c2bfd2d9.png)

**Additional context**
Please provide a create payment example so it's easy for me.

**Comment by chirag2324** [comment]
Hello there,

Please help me out my work is stuck for only this thing.

Thanks in advance.

**Comment by wobinb** [comment]
When creating what will become a PUT or POST request you generally need to place the object ($payment - in this case) into an array, and then pass the array to the createPayment function.
