### ISSUE TITLE
BUG IN IdentityObjectSerializer.php

### ISSUE THREAD

**Issue by jplevene** [XeroAPI/xero-php-oauth2#93]
- Version [1.1] (I am using PHP 7.0 but the code in question is the same for 1.4)

I am getting an error when running the following script copied from your examples on the OAuth2 callback:
```
$config = XeroAPI\XeroPHP\Configuration::getDefaultConfiguration()->setAccessToken( (string)$this->accessTokenObj->getToken() );
$identityApi = new XeroAPI\XeroPHP\Api\IdentityApi( new GuzzleHttp\Client(), $config );
$result = $identityApi->getConnections();
```
The bug is on the `$result = $identityApi->getConnections();` call.

If in the file `/lib/Api/IdentityApi.php`, if I change the code in line 388 from
`IdentityObjectSerializer::deserialize($content, '\XeroAPI\XeroPHP\Models\Identity\Connection[]', []),`
To
`json_decode($content)`
All is good and it works fine, if I leave in the original line, I am left hanging.  The bug seems to be in `IdentityObjectSerializer.php` in the `deserialize(...)` function.

In my code, the code block is being called from inside a function in my own class, so this might be triggering the bug, as all your examples are outside the confines of a function and/or another class.

**Comment by SidneyAllen** [comment]
@jplevene - We are building and testing against PHP version 7.2.1.

The IdentityObjectSerializer functions properly with that version.  We deserialize into the corresponding Model in this case "Connections".  I don't think json_decode($content) is the appropriate substitute as I assume that just returns a JSON object.

Can you try installing version 1.5.0 and see if you are still experiencing this issue?

**Comment by jplevene** [comment]
Sorry, I never used the APi in the end and just wrote my own interface as I was on a deadline
