### ISSUE TITLE
Request timeout due to too much data with client.api list

### ISSUE THREAD

**Issue by landyXU** [XeroAPI/xero-php-oauth2#99]
**Describe the problem**
Request timeout due to too much data with client api list all.

**Request api**
https://api.xero.com/practicemanager/3.0/client.api/list

**Proposal**
Add page params to client.api, I can get it in bratches.
It's ok ?
Please help me,Thanks!

**Comment by SidneyAllen** [comment]
@landyXU - we don't currently support practice manager API endpoints in this SDK.
Please see the README for the API endpoint sets that are supported and have been tested. https://github.com/XeroAPI/xero-php-oauth2

You are free to use the PHP League OAuth 2 library with or without the SDK (we've bundled it with our SDK), but there isn't anything practice API specific in the SDK.
https://github.com/thephpleague/oauth2-client

@TheRegan

**Comment by TheRegan** [comment]
@landyXU could you please lodge a support ticket with us about this here: https://developer.xero.com/contact-xero-developer-platform-support/ we would love  to get some more details.
